// Bus master table from College_310_Bus_Details_Updated.docx
// Each entry: { busNumber, route, driverName, driverPhone, busType, ground }
module.exports = [
  { busNumber: "100", route: "Gokavaram Bus Stand", driverName: "Prasad Rao", driverPhone: "+91-9931863125", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "104", route: "Ramachandrapuram Bus Stand", driverName: "Mohan Chowdary", driverPhone: "+91-9730286002", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "106", route: "Danavaipeta", driverName: "Mahesh Murthy", driverPhone: "+91-9731516849", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "108", route: "Mandapeta Bus Stand", driverName: "Chandra Patel", driverPhone: "+91-9565491039", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "109", route: "Kotagummam", driverName: "Raju Raju", driverPhone: "+91-9206217491", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "111", route: "Ramachandrapuram RTC Complex", driverName: "Mahesh Prasad", driverPhone: "+91-9734197396", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "112", route: "Mandapeta RTC Complex", driverName: "Sekhar Babu", driverPhone: "+91-9442512894", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "116", route: "Tuni Bus Station", driverName: "Nagaraju Yadav", driverPhone: "+91-9822160155", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "118", route: "Mandapeta Main Road", driverName: "Rajesh Yadav", driverPhone: "+91-9921820721", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "119", route: "Arthamuru Junction", driverName: "Mahesh Patel", driverPhone: "+91-9678169927", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "121", route: "Kovvur Bus Stand", driverName: "Nagaraju Rao", driverPhone: "+91-9826253503", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "122", route: "Tuni RTC Complex", driverName: "Raju Murthy", driverPhone: "+91-9455876870", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "123", route: "Yanam French Colony", driverName: "Kumar Reddy", driverPhone: "+91-9561065370", busType: "Faculty Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "124", route: "Ravulapalem Bus Stand", driverName: "Venkat Sharma", driverPhone: "+91-9715739594", busType: "Faculty Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "126", route: "Kovvur RTC Complex", driverName: "Rajesh Chowdary", driverPhone: "+91-9479577660", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "127", route: "Gokavaram RTC Complex", driverName: "Prasad Kumar", driverPhone: "+91-9435829822", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "128", route: "Chinadevarapudi Cross", driverName: "Anil Varma", driverPhone: "+91-9491044359", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "129", route: "Kovvur Main Road", driverName: "Raju Rao", driverPhone: "+91-9291253584", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "132", route: "Yeleswaram Bus Stand", driverName: "Ramesh Das", driverPhone: "+91-9488858849", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "134", route: "Yeleswaram RTC Complex", driverName: "Sekhar Murthy", driverPhone: "+91-9191685362", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "135", route: "Tuni Main Road", driverName: "Chandra Raju", driverPhone: "+91-9188763163", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "136", route: "Tuni Railway Station Road", driverName: "Ramesh Yadav", driverPhone: "+91-9880873717", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "138", route: "Bhanugudi Junction", driverName: "Anil Reddy", driverPhone: "+91-9803336026", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "140", route: "Yeleswaram Main Road", driverName: "Prasad Varma", driverPhone: "+91-9308904721", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "141", route: "Dwarapudi Road", driverName: "Sekhar Prasad", driverPhone: "+91-9966006148", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "143", route: "Bhadravaram Road", driverName: "Mahesh Yadav", driverPhone: "+91-9620550700", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "145", route: "Gokavaram Main Road", driverName: "Ramesh Rao", driverPhone: "+91-9153250484", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "147", route: "Ravulapalem RTC Complex", driverName: "Mohan Prasad", driverPhone: "+91-9133020464", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "148", route: "Dharmavaram Road", driverName: "Venkat Rao", driverPhone: "+91-9925441101", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "149", route: "Ramachandrapuram Main Road", driverName: "Srinu Rao", driverPhone: "+91-9925717860", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "150", route: "Goshpada Kshetram Road", driverName: "Chandra Varma", driverPhone: "+91-9244792106", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "154", route: "Atchutapuram Junction", driverName: "Mahesh Varma", driverPhone: "+91-9562801816", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "155", route: "Yanam Beach Road", driverName: "Naresh Sharma", driverPhone: "+91-9595863660", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "156", route: "Bhupatipalem Cross Road", driverName: "Venkat Chowdary", driverPhone: "+91-9190471339", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "157", route: "Ippanapadu Junction", driverName: "Venkat Sharma", driverPhone: "+91-9505129064", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "158", route: "Kesavaram Cross", driverName: "Satish Murthy", driverPhone: "+91-9502307683", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "159", route: "Main Road", driverName: "Sekhar Sharma", driverPhone: "+91-9363574830", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "160", route: "East Lakshmipuram Junction", driverName: "Nagaraju Das", driverPhone: "+91-9973403211", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "161", route: "Maredubaka Road", driverName: "Chandra Reddy", driverPhone: "+91-9295580364", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "162", route: "ADB Road", driverName: "Rajesh Kumar", driverPhone: "+91-9788760375", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "164", route: "J. Annavaram Road", driverName: "Prasad Naidu", driverPhone: "+91-9865318075", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "166", route: "Ravulapalem Main Road", driverName: "Suresh Reddy", driverPhone: "+91-9305738747", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "167", route: "Kotananduru Road", driverName: "Vijay Rao", driverPhone: "+91-9340955998", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "168", route: "Adivarapupeta Junction", driverName: "Venkat Sharma", driverPhone: "+91-9160243433", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "169", route: "Lakkavaram Cross", driverName: "Sekhar Chowdary", driverPhone: "+91-9917191225", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "170", route: "Draksharama Road", driverName: "Raju Kumar", driverPhone: "+91-9335588812", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "173", route: "Big Market Street", driverName: "Sekhar Kumar", driverPhone: "+91-9714542843", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "177", route: "Chodavaram Cross", driverName: "Mohan Kumar", driverPhone: "+91-9994534794", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "179", route: "Devarapalle Road", driverName: "Naresh Rao", driverPhone: "+91-9446450797", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "182", route: "Sarpavaram Junction", driverName: "Suresh Patel", driverPhone: "+91-9514679647", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "185", route: "Gandhi Nagar", driverName: "Ravi Murthy", driverPhone: "+91-9686402007", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "187", route: "Kovvur Railway Station Road", driverName: "Nagaraju Yadav", driverPhone: "+91-9102976093", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "188", route: "Lingamparthi Junction", driverName: "Raju Reddy", driverPhone: "+91-9818851121", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "189", route: "Thondangi Road", driverName: "Venkat Sharma", driverPhone: "+91-9564017977", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "192", route: "Kandulapalem Junction", driverName: "Chandra Chowdary", driverPhone: "+91-9782078933", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "194", route: "Sankhavaram Junction", driverName: "Ravi Rao", driverPhone: "+91-9844519449", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "195", route: "Gadelapalem Road", driverName: "Ramesh Varma", driverPhone: "+91-9935971656", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "197", route: "Ramanayyapeta", driverName: "Ramesh Chowdary", driverPhone: "+91-9145155947", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "200", route: "Tetagunta Road", driverName: "Rajesh Varma", driverPhone: "+91-9534565230", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "201", route: "Yanam Custom House Road", driverName: "Vijay Prasad", driverPhone: "+91-9499609435", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "204", route: "Innespeta", driverName: "Raju Reddy", driverPhone: "+91-9452672944", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "205", route: "Gummalladuddi Junction", driverName: "Mohan Varma", driverPhone: "+91-9267461433", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "207", route: "Gopalapuram Junction", driverName: "Ramesh Kumar", driverPhone: "+91-9875178305", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "208", route: "Ithakota Cross", driverName: "Mahesh Prasad", driverPhone: "+91-9404149044", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "210", route: "Meruipadu Junction", driverName: "Sekhar Sharma", driverPhone: "+91-9977954273", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "214", route: "Palathodu Cross", driverName: "Ravi Babu", driverPhone: "+91-9396493881", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "215", route: "Yanam Gandhi Park Road", driverName: "Mohan Rao", driverPhone: "+91-9914568736", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "216", route: "Kapavaram Road", driverName: "Mahesh Patel", driverPhone: "+91-9371388344", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "217", route: "Kothapalle Road", driverName: "Prasad Prasad", driverPhone: "+91-9825140279", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "218", route: "Tadipalle Cross", driverName: "Kumar Prasad", driverPhone: "+91-9814276701", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "219", route: "Tandava Sugars Factory Road", driverName: "Mohan Chowdary", driverPhone: "+91-9448521600", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "221", route: "Vakalapudi", driverName: "Sekhar Naidu", driverPhone: "+91-9903970894", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "222", route: "Tapeswaram Road", driverName: "Mohan Prasad", driverPhone: "+91-9249820333", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "223", route: "Tallapolam Junction", driverName: "Venkat Prasad", driverPhone: "+91-9436491958", busType: "Faculty Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "224", route: "Velagathodu Junction", driverName: "Anil Sharma", driverPhone: "+91-9525287629", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "226", route: "Godavari Bridge Approach (Kovvur)", driverName: "Srinu Kumar", driverPhone: "+91-9422886447", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "228", route: "Krishnunipalem Junction", driverName: "Ravi Yadav", driverPhone: "+91-9518626035", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "229", route: "Indrapalem", driverName: "Vijay Naidu", driverPhone: "+91-9803015321", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "230", route: "Farampeta", driverName: "Naresh Yadav", driverPhone: "+91-9839859066", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "231", route: "Syamala Nagar", driverName: "Chandra Naidu", driverPhone: "+91-9798040120", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "232", route: "Turangi", driverName: "Mahesh Naidu", driverPhone: "+91-9905875935", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "233", route: "Mallavaram Cross", driverName: "Naresh Sharma", driverPhone: "+91-9740443743", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "234", route: "Rayudupalem", driverName: "Srinivas Murthy", driverPhone: "+91-9670964448", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "235", route: "Cashew Factory Road", driverName: "Mohan Kumar", driverPhone: "+91-9299220011", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "236", route: "Gandhipuram", driverName: "Suresh Raju", driverPhone: "+91-9532650849", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "239", route: "Rampa Yerrampalem Road", driverName: "Srinivas Raju", driverPhone: "+91-9103371697", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "240", route: "Auto Nagar", driverName: "Vijay Kumar", driverPhone: "+91-9253224258", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "241", route: "Pasivedala Road", driverName: "Prasad Varma", driverPhone: "+91-9650347064", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "242", route: "Vadapalli Cross", driverName: "Chandra Yadav", driverPhone: "+91-9592247914", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "243", route: "Munikoodali Road", driverName: "Anil Reddy", driverPhone: "+91-9435245217", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "245", route: "Ramachandraraopeta", driverName: "Nagaraju Murthy", driverPhone: "+91-9169817927", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "246", route: "Marriveedu Road", driverName: "Srinivas Prasad", driverPhone: "+91-9385997857", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "247", route: "Sivaramapatnam Junction", driverName: "Satish Patel", driverPhone: "+91-9250775262", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "250", route: "Kanakalapeta", driverName: "Ramesh Raju", driverPhone: "+91-9391131030", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "251", route: "Mango Market Junction", driverName: "Sekhar Sharma", driverPhone: "+91-9523027155", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "252", route: "Seetayyapalem Cross", driverName: "Satish Das", driverPhone: "+91-9155520976", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "253", route: "Prakasam Nagar", driverName: "Chandra Chowdary", driverPhone: "+91-9309880748", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "254", route: "Juthigapadu Road", driverName: "Naresh Das", driverPhone: "+91-9335548606", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "255", route: "Yeditha Road", driverName: "Suresh Raju", driverPhone: "+91-9217352036", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "256", route: "Peddanapalle Cross", driverName: "Prasad Yadav", driverPhone: "+91-9240435064", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "258", route: "Sudikonda Road", driverName: "Venkat Prasad", driverPhone: "+91-9436561463", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "259", route: "Brahmanagudem Junction", driverName: "Ravi Naidu", driverPhone: "+91-9170369198", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "262", route: "Komaraju Lanka Junction", driverName: "Kumar Das", driverPhone: "+91-9535043920", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "263", route: "Tuni Market Junction", driverName: "Kumar Prasad", driverPhone: "+91-9938405130", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "265", route: "Jampeta", driverName: "Mahesh Naidu", driverPhone: "+91-9205293492", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "266", route: "Venkat Nagar", driverName: "Satish Kumar", driverPhone: "+91-9534096975", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "267", route: "Z.Medapadu Junction", driverName: "Naresh Varma", driverPhone: "+91-9375053998", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "268", route: "Kambala Peta", driverName: "Chandra Raju", driverPhone: "+91-9550091733", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "271", route: "Metturu", driverName: "Mahesh Chowdary", driverPhone: "+91-9299859510", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "274", route: "Mandapeta Market Junction", driverName: "Raju Babu", driverPhone: "+91-9380547405", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "275", route: "Peravaram Junction", driverName: "Raju Rao", driverPhone: "+91-9279022732", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "276", route: "Ramanayyapeta Road (Yeleswaram)", driverName: "Naresh Babu", driverPhone: "+91-9993115833", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "277", route: "Togummi Cross", driverName: "Chandra Yadav", driverPhone: "+91-9690596876", busType: "Faculty Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "279", route: "Chagallu Road", driverName: "Vijay Naidu", driverPhone: "+91-9860647538", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "280", route: "Thotapeta Road", driverName: "Raju Sharma", driverPhone: "+91-9258787406", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "281", route: "Tuni High School Road", driverName: "Kumar Varma", driverPhone: "+91-9575420567", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "282", route: "Mandapeta High School Road", driverName: "Chandra Reddy", driverPhone: "+91-9216590336", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "283", route: "Mandapeta ZP School Road", driverName: "Ramesh Kumar", driverPhone: "+91-9437421743", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "284", route: "Kovvur Market Junction", driverName: "Suresh Sharma", driverPhone: "+91-9603297689", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "285", route: "Siripuram Cross", driverName: "Nagaraju Raju", driverPhone: "+91-9755154819", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "286", route: "Tuni ZP School Road", driverName: "Kumar Sharma", driverPhone: "+91-9490724578", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "288", route: "Agraharam Street", driverName: "Nagaraju Kumar", driverPhone: "+91-9943539870", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "291", route: "Darsanam Street", driverName: "Venkat Murthy", driverPhone: "+91-9726177555", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "293", route: "Tuni Canal Bridge", driverName: "Ramesh Chowdary", driverPhone: "+91-9776962229", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "294", route: "Vegayammapeta Cross", driverName: "Ramesh Rao", driverPhone: "+91-9130920499", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "295", route: "Jagannaickpur", driverName: "Naresh Reddy", driverPhone: "+91-9625496923", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "300", route: "Kacheripeta", driverName: "Venkat Patel", driverPhone: "+91-9433065933", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "301", route: "Takurupalem Cross", driverName: "Rajesh Patel", driverPhone: "+91-9910470407", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "302", route: "Tirumali Road", driverName: "Chandra Prasad", driverPhone: "+91-9531694952", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "307", route: "Kambalapalem Junction", driverName: "Suresh Reddy", driverPhone: "+91-9258061705", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "308", route: "Bharathi Street", driverName: "Anil Sharma", driverPhone: "+91-9730230670", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "310", route: "Thantikonda Junction", driverName: "Srinu Chowdary", driverPhone: "+91-9403635497", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "312", route: "Velampalem Junction", driverName: "Kumar Rao", driverPhone: "+91-9538507730", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "313", route: "Ganapavaram Road", driverName: "Rajesh Sharma", driverPhone: "+91-9676325427", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "314", route: "Mandapeta Canal Bridge", driverName: "Raju Sharma", driverPhone: "+91-9773481517", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "315", route: "Lakshmipolavaram Road", driverName: "Ravi Varma", driverPhone: "+91-9441957295", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "319", route: "Venkatayapalem Road", driverName: "Mohan Rao", driverPhone: "+91-9961241720", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "320", route: "Karnamgari Junction", driverName: "Kumar Prasad", driverPhone: "+91-9154796027", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "321", route: "Tuni Anjaneya Temple", driverName: "Raju Das", driverPhone: "+91-9304447050", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "322", route: "Morampudi Road", driverName: "Kumar Sharma", driverPhone: "+91-9734655412", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "326", route: "Mummidivarappadu Cross", driverName: "Anil Patel", driverPhone: "+91-9636854281", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "327", route: "Yerravaram Road", driverName: "Satish Prasad", driverPhone: "+91-9814202212", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "334", route: "Kondayyapalem", driverName: "Naresh Naidu", driverPhone: "+91-9110716661", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "335", route: "Tirumalayapalem Road", driverName: "Ramesh Reddy", driverPhone: "+91-9549650879", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "337", route: "Yeleswaram Market Junction", driverName: "Venkat Rao", driverPhone: "+91-9478983265", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "339", route: "Injaram Road", driverName: "Prasad Reddy", driverPhone: "+91-9136980673", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "340", route: "Gokavaram Market Junction", driverName: "Suresh Varma", driverPhone: "+91-9515967991", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "342", route: "Yeleswaram High School Road", driverName: "Srinu Sharma", driverPhone: "+91-9420106187", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "344", route: "Podagatlapalle Junction", driverName: "Mohan Prasad", driverPhone: "+91-9713768259", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "347", route: "Yeleswaram ZP School Road", driverName: "Mahesh Kumar", driverPhone: "+91-9665129308", busType: "Faculty Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "348", route: "Gokavaram High School Road", driverName: "Suresh Reddy", driverPhone: "+91-9400568384", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "351", route: "Yanam Bus Stand", driverName: "Suresh Naidu", driverPhone: "+91-9423617700", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "352", route: "Yanam RTC Complex", driverName: "Satish Kumar", driverPhone: "+91-9422556023", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "353", route: "Ubalanka Road", driverName: "Satish Rao", driverPhone: "+91-9358583837", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "355", route: "Gokavaram ZP School Road", driverName: "Vijay Babu", driverPhone: "+91-9982842242", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "357", route: "Gokavaram Canal Bridge", driverName: "Naresh Chowdary", driverPhone: "+91-9491136233", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "358", route: "Yanamadala Cross", driverName: "Naresh Prasad", driverPhone: "+91-9962261109", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "363", route: "Madhavapatnam", driverName: "Kumar Das", driverPhone: "+91-9527495043", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "364", route: "Mandapeta Anjaneya Temple", driverName: "Srinivas Prasad", driverPhone: "+91-9218318025", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "366", route: "Vedireswaram Cross", driverName: "Babu Naidu", driverPhone: "+91-9728612045", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "367", route: "Kovvur High School Road", driverName: "Sekhar Sharma", driverPhone: "+91-9603133754", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "370", route: "Narasapurapupeta Road", driverName: "Chandra Chowdary", driverPhone: "+91-9147282138", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "371", route: "Ravulapalem NH16 Junction", driverName: "Chandra Kumar", driverPhone: "+91-9127968174", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "372", route: "Tuni Petrol Bunk Junction", driverName: "Ramesh Das", driverPhone: "+91-9927414533", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "374", route: "Hasanbada Junction", driverName: "Suresh Reddy", driverPhone: "+91-9461849775", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "376", route: "Thadithota", driverName: "Chandra Chowdary", driverPhone: "+91-9900252838", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "377", route: "Mandapeta Petrol Bunk Junction", driverName: "Suresh Varma", driverPhone: "+91-9353940280", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "378", route: "Kovvur ZP School Road", driverName: "Suresh Raju", driverPhone: "+91-9389000432", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "379", route: "Gokavaram Anjaneya Temple", driverName: "Anil Rao", driverPhone: "+91-9866485585", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "380", route: "Ravulapalem Market Junction", driverName: "Babu Kumar", driverPhone: "+91-9780289395", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "381", route: "Oduru Cross", driverName: "Srinivas Das", driverPhone: "+91-9768435728", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "383", route: "Kovvur Canal Bridge", driverName: "Babu Murthy", driverPhone: "+91-9981345124", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "384", route: "Majestic Street", driverName: "Rajesh Babu", driverPhone: "+91-9554232936", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "386", route: "Gokavaram Petrol Bunk Junction", driverName: "Ramesh Yadav", driverPhone: "+91-9747937117", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "387", route: "Balaji Cheruvu Road", driverName: "Naresh Raju", driverPhone: "+91-9663303645", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "389", route: "Kovvur Anjaneya Temple", driverName: "Suresh Yadav", driverPhone: "+91-9650546503", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "390", route: "Yeleswaram Canal Bridge", driverName: "Mohan Murthy", driverPhone: "+91-9663530539", busType: "Faculty Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "391", route: "Diwan Cheruvu", driverName: "Rajesh Patel", driverPhone: "+91-9847946632", busType: "Faculty Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "392", route: "Nagamallithota Junction", driverName: "Suresh Chowdary", driverPhone: "+91-9190557557", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "394", route: "Yanam Main Road", driverName: "Mahesh Raju", driverPhone: "+91-9116921772", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "396", route: "Tuni Sub-Registrar Office Road", driverName: "Mohan Prasad", driverPhone: "+91-9649918266", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "399", route: "Arya Vysya Street", driverName: "Ravi Chowdary", driverPhone: "+91-9152281616", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "400", route: "Kovvur Petrol Bunk Junction", driverName: "Ramesh Chowdary", driverPhone: "+91-9724220078", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "401", route: "Ramachandrapuram Market Junction", driverName: "Prasad Sharma", driverPhone: "+91-9939302093", busType: "Faculty Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "403", route: "Kovvur Sub-Registrar Office Road", driverName: "Kumar Murthy", driverPhone: "+91-9644403907", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "404", route: "Gokavaram Sub-Registrar Office Road", driverName: "Srinu Raju", driverPhone: "+91-9896747291", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "405", route: "Godavari Arch Bridge Road", driverName: "Ravi Reddy", driverPhone: "+91-9484564622", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "406", route: "Yanam Market Junction", driverName: "Kumar Yadav", driverPhone: "+91-9794367427", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "407", route: "Mandapeta Sub-Registrar Office Road", driverName: "Ramesh Yadav", driverPhone: "+91-9795529029", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "408", route: "Yanam High School Road", driverName: "Raju Prasad", driverPhone: "+91-9526608415", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "411", route: "Yanam Canal Bridge", driverName: "Srinu Kumar", driverPhone: "+91-9982259418", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "412", route: "Yanam Anjaneya Temple", driverName: "Prasad Raju", driverPhone: "+91-9649460460", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "413", route: "Yeleswaram Anjaneya Temple", driverName: "Sekhar Kumar", driverPhone: "+91-9778391994", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "414", route: "NFCL Road", driverName: "Anil Prasad", driverPhone: "+91-9868052356", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "416", route: "Ramachandrapuram High School Road", driverName: "Kumar Das", driverPhone: "+91-9331744197", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "418", route: "Kovvur Co-operative Society Road", driverName: "Ramesh Rao", driverPhone: "+91-9203252798", busType: "Faculty Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "419", route: "Tuni Co-operative Society Road", driverName: "Satish Babu", driverPhone: "+91-9586247020", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "420", route: "Yeleswaram Petrol Bunk Junction", driverName: "Mohan Kumar", driverPhone: "+91-9141039232", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "421", route: "Ravulapalem High School Road", driverName: "Raju Das", driverPhone: "+91-9761579764", busType: "Faculty Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "424", route: "Tuni Vegetable Market", driverName: "Prasad Reddy", driverPhone: "+91-9895775905", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "426", route: "Yanam Petrol Bunk Junction", driverName: "Venkat Babu", driverPhone: "+91-9916013240", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "433", route: "Yanam Sub-Registrar Office Road", driverName: "Suresh Das", driverPhone: "+91-9725773654", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "434", route: "Ravulapalem ZP School Road", driverName: "Vijay Rao", driverPhone: "+91-9714065375", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "437", route: "Ramachandrapuram ZP School Road", driverName: "Anil Kumar", driverPhone: "+91-9481109386", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "439", route: "Ramachandrapuram Canal Bridge", driverName: "Vijay Raju", driverPhone: "+91-9209480035", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "442", route: "Kovvur Vegetable Market", driverName: "Nagaraju Murthy", driverPhone: "+91-9338744816", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "445", route: "Mandapeta Co-operative Society Road", driverName: "Anil Chowdary", driverPhone: "+91-9143176460", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "447", route: "Yanam Co-operative Society Road", driverName: "Rajesh Das", driverPhone: "+91-9500446716", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "448", route: "Tuni Water Tank Road", driverName: "Mohan Chowdary", driverPhone: "+91-9129712236", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "450", route: "Kovvur Water Tank Road", driverName: "Srinivas Rao", driverPhone: "+91-9521359009", busType: "Faculty Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "451", route: "Tuni Police Station Road", driverName: "Venkat Yadav", driverPhone: "+91-9942578852", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "456", route: "Railway Station Road", driverName: "Naresh Das", driverPhone: "+91-9173664421", busType: "Faculty Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "457", route: "Ravulapalem Canal Bridge", driverName: "Mohan Naidu", driverPhone: "+91-9272525333", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "458", route: "Old Bus Stand", driverName: "Satish Chowdary", driverPhone: "+91-9124763220", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "459", route: "Gokavaram Co-operative Society Road", driverName: "Rajesh Naidu", driverPhone: "+91-9679251272", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "461", route: "Ontimamidi Junction", driverName: "Kumar Patel", driverPhone: "+91-9611233856", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "462", route: "Pallamraju Nagar", driverName: "Satish Naidu", driverPhone: "+91-9665788808", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "463", route: "Gokavaram Vegetable Market", driverName: "Srinivas Kumar", driverPhone: "+91-9968066385", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "464", route: "Yanam Vegetable Market", driverName: "Ravi Das", driverPhone: "+91-9677493493", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "465", route: "Yeleswaram Sub-Registrar Office Road", driverName: "Sekhar Prasad", driverPhone: "+91-9724508080", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "467", route: "RTC Complex", driverName: "Satish Kumar", driverPhone: "+91-9783645516", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "468", route: "Mandapeta Vegetable Market", driverName: "Mahesh Babu", driverPhone: "+91-9900726697", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "469", route: "Kotipalli Bus Stand", driverName: "Raju Varma", driverPhone: "+91-9200093156", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "472", route: "Mandapeta Water Tank Road", driverName: "Vijay Raju", driverPhone: "+91-9566378787", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "474", route: "Ravulapalem Anjaneya Temple", driverName: "Ravi Sharma", driverPhone: "+91-9625430454", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "475", route: "Port Railway Station Road", driverName: "Srinivas Varma", driverPhone: "+91-9177074918", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "476", route: "Yanam Water Tank Road", driverName: "Venkat Yadav", driverPhone: "+91-9894192359", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "477", route: "Pratap Nagar", driverName: "Mohan Yadav", driverPhone: "+91-9549868718", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "478", route: "Kovvur Police Station Road", driverName: "Suresh Das", driverPhone: "+91-9359478167", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "479", route: "Ramakrishnaraopeta", driverName: "Anil Chowdary", driverPhone: "+91-9703148203", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "482", route: "Kovvur Rice Mill Road", driverName: "Anil Prasad", driverPhone: "+91-9951133448", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "484", route: "Yeleswaram Co-operative Society Road", driverName: "Mohan Prasad", driverPhone: "+91-9505037850", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "486", route: "Yanam Police Station Road", driverName: "Mohan Patel", driverPhone: "+91-9267943155", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "487", route: "Tuni Rice Mill Road", driverName: "Babu Yadav", driverPhone: "+91-9483468904", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "488", route: "Yanam New Colony", driverName: "Srinivas Rao", driverPhone: "+91-9802924397", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "489", route: "Someswara Temple Road", driverName: "Srinu Raju", driverPhone: "+91-9677296212", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "490", route: "Ravulapalem Petrol Bunk Junction", driverName: "Venkat Reddy", driverPhone: "+91-9972297935", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "491", route: "Ramachandrapuram Petrol Bunk Junction", driverName: "Babu Raju", driverPhone: "+91-9846376145", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "494", route: "Yeleswaram Vegetable Market", driverName: "Mohan Kumar", driverPhone: "+91-9216698648", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "496", route: "Ravulapalem Sub-Registrar Office Road", driverName: "Ramesh Yadav", driverPhone: "+91-9616582064", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "497", route: "Devi Chowk", driverName: "Chandra Varma", driverPhone: "+91-9892052106", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "498", route: "Gokavaram Water Tank Road", driverName: "Anil Yadav", driverPhone: "+91-9739513105", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "499", route: "Tuni New Colony", driverName: "Sekhar Yadav", driverPhone: "+91-9680841377", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "500", route: "Ravulapalem Co-operative Society Road", driverName: "Ramesh Chowdary", driverPhone: "+91-9442742902", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "501", route: "Ramaraopeta", driverName: "Ramesh Raju", driverPhone: "+91-9420832967", busType: "Faculty Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "502", route: "Tuni Old Town", driverName: "Anil Varma", driverPhone: "+91-9763431483", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "503", route: "Lalacheruvu", driverName: "Rajesh Reddy", driverPhone: "+91-9755603139", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "504", route: "Mandapeta Police Station Road", driverName: "Raju Patel", driverPhone: "+91-9921863938", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "505", route: "Ravulapalem Vegetable Market", driverName: "Satish Kumar", driverPhone: "+91-9666331197", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "507", route: "Mandapeta Rice Mill Road", driverName: "Suresh Chowdary", driverPhone: "+91-9126630037", busType: "Faculty Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "509", route: "Yeleswaram Water Tank Road", driverName: "Srinu Yadav", driverPhone: "+91-9244159314", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "510", route: "Apsara Theatre Road", driverName: "Nagaraju Varma", driverPhone: "+91-9575057620", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "512", route: "Ravulapalem Water Tank Road", driverName: "Prasad Sharma", driverPhone: "+91-9213821937", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "513", route: "Gokavaram Police Station Road", driverName: "Srinivas Naidu", driverPhone: "+91-9489724215", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "514", route: "Kovvur New Colony", driverName: "Prasad Reddy", driverPhone: "+91-9640690716", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "520", route: "Alcot Gardens Road", driverName: "Srinivas Babu", driverPhone: "+91-9191648443", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "522", route: "Suryanarayanapuram", driverName: "Nagaraju Babu", driverPhone: "+91-9285752985", busType: "Faculty Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "523", route: "Ravulapalem Police Station Road", driverName: "Nagaraju Reddy", driverPhone: "+91-9863891379", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "524", route: "Yeleswaram Police Station Road", driverName: "Mohan Raju", driverPhone: "+91-9698580730", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "525", route: "Suryaraopet", driverName: "Prasad Varma", driverPhone: "+91-9808000008", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "526", route: "Ramachandrapuram Sub-Registrar Office Road", driverName: "Mohan Patel", driverPhone: "+91-9568112228", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "527", route: "Vidyanagar", driverName: "Venkat Chowdary", driverPhone: "+91-9465337844", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "529", route: "T Nagar", driverName: "Kumar Chowdary", driverPhone: "+91-9659302777", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "530", route: "Gokavaram Rice Mill Road", driverName: "Venkat Yadav", driverPhone: "+91-9805912741", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "531", route: "Mandapeta New Colony", driverName: "Mohan Reddy", driverPhone: "+91-9491498382", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "532", route: "Bommuru", driverName: "Srinu Kumar", driverPhone: "+91-9616823081", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "533", route: "Mandapeta Old Town", driverName: "Satish Reddy", driverPhone: "+91-9450381461", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "534", route: "Tuni Railway Gate", driverName: "Satish Kumar", driverPhone: "+91-9996675187", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "535", route: "Ravulapalem Rice Mill Road", driverName: "Nagaraju Naidu", driverPhone: "+91-9573687284", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "538", route: "Yeleswaram Rice Mill Road", driverName: "Srinivas Rao", driverPhone: "+91-9632454023", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "539", route: "Kovvur Old Town", driverName: "Raju Rao", driverPhone: "+91-9760363114", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "541", route: "Ravulapalem New Colony", driverName: "Naresh Varma", driverPhone: "+91-9563864843", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "542", route: "Yanam Old Town", driverName: "Mohan Babu", driverPhone: "+91-9971850349", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "543", route: "Temple Street", driverName: "Srinu Murthy", driverPhone: "+91-9888467476", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "544", route: "Tilak Street", driverName: "Ravi Rao", driverPhone: "+91-9423392902", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "545", route: "Rangachary Street", driverName: "Chandra Murthy", driverPhone: "+91-9738330383", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "546", route: "Yanam Railway Gate", driverName: "Ramesh Raju", driverPhone: "+91-9730994393", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "548", route: "Kovvur Railway Gate", driverName: "Suresh Das", driverPhone: "+91-9815133365", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "549", route: "Lalitha Nagar", driverName: "Ramesh Rao", driverPhone: "+91-9322665575", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "550", route: "Vysyanagar", driverName: "Mahesh Sharma", driverPhone: "+91-9440074199", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "553", route: "Mandapeta Railway Gate", driverName: "Raju Varma", driverPhone: "+91-9673443608", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "556", route: "Yanam Housing Board Colony", driverName: "Nagaraju Varma", driverPhone: "+91-9778275498", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "558", route: "Ravulapalem Old Town", driverName: "Satish Patel", driverPhone: "+91-9556558948", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "559", route: "Ramachandrapuram Co-operative Society Road", driverName: "Srinu Kumar", driverPhone: "+91-9706209602", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "560", route: "Yanam Weavers Colony", driverName: "Srinu Babu", driverPhone: "+91-9592834873", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "561", route: "Anandavaram", driverName: "Raju Reddy", driverPhone: "+91-9798590911", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "562", route: "Gokavaram New Colony", driverName: "Prasad Chowdary", driverPhone: "+91-9735669858", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "563", route: "Ramachandrapuram Vegetable Market", driverName: "Vijay Sharma", driverPhone: "+91-9107112263", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "565", route: "Yeleswaram New Colony", driverName: "Ramesh Patel", driverPhone: "+91-9523769738", busType: "Faculty Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "566", route: "Ramachandrapuram Water Tank Road", driverName: "Naresh Naidu", driverPhone: "+91-9296055755", busType: "Faculty Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "569", route: "Chuttugunta Junction", driverName: "Mahesh Patel", driverPhone: "+91-9992429140", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "571", route: "Kovvur Housing Board Colony", driverName: "Venkat Sharma", driverPhone: "+91-9697447589", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "572", route: "Tuni Housing Board Colony", driverName: "Nagaraju Babu", driverPhone: "+91-9156917540", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "574", route: "Tuni Weavers Colony", driverName: "Ravi Naidu", driverPhone: "+91-9726419300", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "577", route: "Ramachandrapuram Police Station Road", driverName: "Naresh Varma", driverPhone: "+91-9633592450", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "579", route: "Ramachandrapuram Old Town", driverName: "Mohan Naidu", driverPhone: "+91-9836016066", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "580", route: "Kovvur Weavers Colony", driverName: "Nagaraju Raju", driverPhone: "+91-9641950050", busType: "Faculty Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "581", route: "Gokavaram Railway Gate", driverName: "Suresh Raju", driverPhone: "+91-9344864565", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "582", route: "Ravulapalem Railway Gate", driverName: "Chandra Reddy", driverPhone: "+91-9736189126", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "584", route: "Tuni Stadium Road", driverName: "Ravi Yadav", driverPhone: "+91-9869103442", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "585", route: "Tuni Degree College Road", driverName: "Kumar Das", driverPhone: "+91-9260880186", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "586", route: "Yeleswaram Old Town", driverName: "Prasad Chowdary", driverPhone: "+91-9628396361", busType: "Student Bus", ground: "Peddapuram Bus Ground" },
  { busNumber: "587", route: "Kovvur Stadium Road", driverName: "Chandra Babu", driverPhone: "+91-9330199243", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "589", route: "Ramachandrapuram Railway Gate", driverName: "Nagaraju Kumar", driverPhone: "+91-9242824519", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "590", route: "Gokavaram Old Town", driverName: "Ramesh Raju", driverPhone: "+91-9194265127", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "595", route: "Yanam Stadium Road", driverName: "Chandra Raju", driverPhone: "+91-9299010360", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "596", route: "Ravulapalem Housing Board Colony", driverName: "Suresh Chowdary", driverPhone: "+91-9162348014", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "597", route: "Yeleswaram Railway Gate", driverName: "Ravi Das", driverPhone: "+91-9311227887", busType: "Student Bus", ground: "Rajahmundry Bus Ground" },
  { busNumber: "598", route: "Ravulapalem Weavers Colony", driverName: "Suresh Naidu", driverPhone: "+91-9677610850", busType: "Student Bus", ground: "Kakinada Bus Ground" },
  { busNumber: "599", route: "Tuni Junior College Road", driverName: "Mohan Chowdary", driverPhone: "+91-9742650106", busType: "Student Bus", ground: "Kakinada Bus Ground" },
];
module.exports.length = 310;

