// Faculty master table from Aditya_Surampalem_Faculty_Master_Table.docx
// Each entry: { id, name, department, role }
module.exports = [
  { id: "F001", name: "Dr. Bellum Ramamohan Reddy", department: "Civil Engineering", role: "Assistant Professor & HOD" },
  { id: "F002", name: "Dr. Anjali R", department: "Civil Engineering", role: "Faculty" },
  { id: "F003", name: "Dr. S Govindarajan", department: "Civil Engineering", role: "Faculty" },
  { id: "F004", name: "Dr. Pachaiappan S", department: "Civil Engineering", role: "Faculty" },
  { id: "F005", name: "Dr. S Anandha Kumar", department: "Civil Engineering", role: "Faculty" },
  { id: "F006", name: "Dr. Yaswanth K K", department: "Civil Engineering", role: "Faculty" },
  { id: "F007", name: "Dr. Pasupuleti Laxmi Narayana", department: "Civil Engineering", role: "Faculty" },
  { id: "F008", name: "Dr. Talapareddy Suman Kumar", department: "Civil Engineering", role: "Faculty" },
  { id: "F009", name: "Dr. Ch Naga Dheeraj Kumar Reddy", department: "Civil Engineering", role: "Faculty" },
  { id: "F010", name: "Dr. Tammineni Gnananandarao", department: "Civil Engineering", role: "Faculty" },
  { id: "F011", name: "Dr. Muthyala Sai Chaithanya", department: "Civil Engineering", role: "Faculty" },
  { id: "F012", name: "Dr. Chappa Ajay", department: "Civil Engineering", role: "Faculty" },
  { id: "F013", name: "Mr. Penugonda Shiva Kumar", department: "Civil Engineering", role: "Faculty" },
  { id: "F014", name: "Ms. Panuganti Lakshmi", department: "Civil Engineering", role: "Faculty" },
  { id: "F015", name: "Mr. Gaddam Dinesh", department: "Civil Engineering", role: "Faculty" },
  { id: "F016", name: "Mr. Borra Ramsagar", department: "Civil Engineering", role: "Faculty" },
  { id: "F017", name: "Mr. Nalli Bhaskara Rao", department: "Civil Engineering", role: "Faculty" },
  { id: "F018", name: "Ms. Nataru Anusha", department: "Civil Engineering", role: "Faculty" },
  { id: "F019", name: "Mr. Bandi Maheswara Rao", department: "Civil Engineering", role: "Faculty" },
  { id: "F020", name: "Dr. Veeranki Srinivasa Rao", department: "Civil Engineering", role: "Associate Professor & HOD" },
  { id: "F021", name: "Dr. A Ramesh", department: "University Administration", role: "Pro Vice-Chancellor (Engg. & Sciences)" },
  { id: "F022", name: "Dr. Jonnalagadda Pavan", department: "Examinations", role: "Controller of Examinations" },
  { id: "F023", name: "Dr. Keerty Vs Ramachandra Murthy", department: "Civil Engineering", role: "Faculty" },
  { id: "F024", name: "Dr. Boddepalli Rajani", department: "Civil Engineering", role: "Faculty" },
  { id: "F025", name: "Dr. Kommula Bapayya Naidu", department: "Civil Engineering", role: "Faculty" },
  { id: "F026", name: "Dr. Kothalanka K Pavan Kumar", department: "Civil Engineering", role: "Faculty" },
  { id: "F027", name: "Dr. Ramudu Ganji", department: "Civil Engineering", role: "Faculty" },
  { id: "F028", name: "Dr. Manam Ravindra", department: "Civil Engineering", role: "Faculty" },
  { id: "F029", name: "Dr. Pydi Bala Krishna", department: "Civil Engineering", role: "Faculty" },
  { id: "F030", name: "Dr. Vijay Muniyandi", department: "Civil Engineering", role: "Faculty" },
  { id: "F031", name: "Dr. Balla Sri Satya Ganesh Pardhu", department: "Civil Engineering", role: "Faculty" },
  { id: "F032", name: "Mr. Ballekura Veeranarayana", department: "Civil Engineering", role: "Faculty" },
  { id: "F033", name: "Mr. Kasukurthi Rambabu", department: "Civil Engineering", role: "Faculty" },
  { id: "F034", name: "Mr. Chakka Bapi Ayyappa Raju", department: "Civil Engineering", role: "Faculty" },
  { id: "F035", name: "Ms. Kunduru Sandhya Rani", department: "Civil Engineering", role: "Faculty" },
  { id: "F036", name: "Mr. Kurra Venkateswara Rao", department: "Civil Engineering", role: "Faculty" },
  { id: "F037", name: "Mr. Vadrevu Ramakrishna", department: "Civil Engineering", role: "Faculty" },
  { id: "F038", name: "Ms. Kambampati Lakshmi", department: "Civil Engineering", role: "Faculty" },
  { id: "F039", name: "Ms. Vemana U P Lavanya", department: "Civil Engineering", role: "Faculty" },
  { id: "F040", name: "Ms. Tata Himaja", department: "Civil Engineering", role: "Faculty" },
  { id: "F041", name: "Dr. Saragada D V V S Bhimeshwar Reddy", department: "Mechanical Engineering", role: "Assistant Professor & HOD" },
  { id: "F042", name: "Dr. Medapati Sreenivasa Reddy", department: "University Administration", role: "Dy. Pro-Chancellor" },
  { id: "F043", name: "Dr. A Saravanan", department: "Research & Consultancy", role: "Dean - Research & Consultancy" },
  { id: "F044", name: "Dr. Subrahmanya Ranjit Pasupuleti", department: "International Relations", role: "Dean - International Relations" },
  { id: "F045", name: "Dr. Elumalai P V", department: "School of Engineering", role: "Faculty" },
  { id: "F046", name: "Dr. Varaprasad Bhemuni", department: "School of Engineering", role: "Faculty" },
  { id: "F047", name: "Dr. Y Krishna Srinivasa Subba Rao", department: "Student Welfare", role: "Dean - Student Welfare" },
  { id: "F048", name: "Dr. Akhilesh Kumar Singh", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F049", name: "Dr. Pritam Kumar Das", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F050", name: "Dr. Sandip Kunar", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F051", name: "Dr. Mohammed Zubairuddin", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F052", name: "Dr. G V Krishna Pradeep", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F053", name: "Dr. Uzwalkiran Rokkala", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F054", name: "Dr. Nitla Stanley Ebenezer", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F055", name: "Dr. N Bhanu Teja", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F056", name: "Dr. Ch V V M J Satish", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F057", name: "Dr. Abbireddy Sridhar Reddy", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F058", name: "Dr. Dara Ram Babu", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F059", name: "Mr. Karedla Lakshmi Kishore", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F060", name: "Mr. J D Venkatesh", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F061", name: "Ms. Varasala Pragna", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F062", name: "Mr. Adduri S S M Sita Rama Murthy", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F063", name: "Mr. Pandiri Jaikishan", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F064", name: "Ms. Mylavarapu Anusha", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F065", name: "Mr. Kadupu Rakesh Varma", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F066", name: "Mr. Sundarapalli Ganapathi", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F067", name: "Mr. Subrahmanyam S", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F068", name: "Mr. Ram Babu Muppidi", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F069", name: "Mr. Yadluri Ravi Kishore", department: "Mechanical Engineering", role: "Faculty" },
  { id: "F070", name: "Dr. M. B. Srinivas", department: "University Administration", role: "Vice Chancellor" },
  { id: "F071", name: "Dr. Gulivindala Suresh", department: "University Administration", role: "Registrar" },
  { id: "F072", name: "Dr. Gamini Sridevi", department: "School of Engineering", role: "Dean - School of Engineering" },
  { id: "F073", name: "Dr. Mahesh Kumar Singh", department: "School of Engineering", role: "Faculty" },
  { id: "F074", name: "Dr. R V V Krishna", department: "School of Engineering", role: "Faculty" },
  { id: "F075", name: "Dr. G Rama Krishna", department: "IQAC", role: "Dean - IQAC" },
  { id: "F076", name: "Dr. Sanjeev Kumar", department: "School of Engineering", role: "Faculty" },
  { id: "F077", name: "Dr. Kondru Ayyappa Swamy", department: "Academics", role: "Associate Dean - Academics" },
  { id: "F078", name: "Dr. D Kishore", department: "Student Affairs", role: "Dean - Students Affairs" },
  { id: "F079", name: "Dr. Nainavarapu Radha", department: "School of Engineering", role: "Faculty" },
  { id: "F080", name: "Dr. Rajyalakshmi Uppada", department: "School of Engineering", role: "Faculty" },
  { id: "F081", name: "Dr. Arigela Laxmana Siridhara", department: "School of Engineering", role: "Faculty" },
  { id: "F082", name: "Dr. Tathababu Addepalli", department: "School of Engineering", role: "Faculty" },
  { id: "F083", name: "Dr. Pamarthi Sunitha", department: "School of Engineering", role: "Faculty" },
  { id: "F084", name: "Dr. Padarti Vijayakumar", department: "School of Engineering", role: "Faculty" },
  { id: "F085", name: "Dr. Ch Venkata Ravisankar", department: "School of Engineering", role: "Faculty" },
  { id: "F086", name: "Dr. Kama Ramudu", department: "School of Engineering", role: "Faculty" },
  { id: "F087", name: "Dr. Gudivada A Arun Kumar", department: "School of Engineering", role: "Faculty" },
  { id: "F088", name: "Dr. Narla Venkata Lalitha", department: "School of Engineering", role: "Faculty" },
  { id: "F089", name: "Dr. R Anil Kumar", department: "School of Engineering", role: "Faculty" },
  { id: "F090", name: "Dr. Chukka Rajasekhar", department: "School of Engineering", role: "Faculty" },
  { id: "F091", name: "Mr. Vella Satyanarayana", department: "Campus Life Management", role: "Dean - Campus Life Management" },
  { id: "F092", name: "Mr. Satti Hari Chandra Prasad", department: "Examinations", role: "Deputy Controller of Exams" },
  { id: "F093", name: "Dr. Jagatpati Raiguru", department: "School of Engineering", role: "Faculty" },
  { id: "F094", name: "Dr. Akash Kumar Gupta", department: "School of Engineering", role: "Faculty" },
  { id: "F095", name: "Dr. Manumula Srinubabu", department: "School of Engineering", role: "Faculty" },
  { id: "F096", name: "Dr. Narayana Rao Pallepu", department: "School of Engineering", role: "Faculty" },
  { id: "F097", name: "Dr. Mahesh Babu Kota", department: "Research & Consultancy", role: "Co-Ordinator - Research & Consultancy" },
  { id: "F098", name: "Dr. Inakoti Ramesh Raja", department: "School of Engineering", role: "Faculty" },
  { id: "F099", name: "Dr. Garaga Srilakshmi", department: "School of Engineering", role: "Faculty" },
  { id: "F100", name: "Dr. Adiraju Rama Vasantha", department: "School of Engineering", role: "Faculty" },
  { id: "F101", name: "Dr. Mandipudi Raghunath", department: "School of Engineering", role: "Faculty" },
  { id: "F102", name: "Dr. R Raman", department: "School of Engineering", role: "Faculty" },
  { id: "F103", name: "Dr. Penumutchi Bujji Babu", department: "School of Engineering", role: "Faculty" },
  { id: "F104", name: "Dr. Raveendra Pilli", department: "School of Engineering", role: "Faculty" },
  { id: "F105", name: "Dr. Chintha Sri Pothu Raju", department: "School of Engineering", role: "Faculty" },
  { id: "F106", name: "Ms. Paluri Krishna Veni", department: "School of Engineering", role: "Faculty" },
  { id: "F107", name: "Dr. Hanumanthkrishnaprasad K", department: "School of Engineering", role: "Faculty" },
  { id: "F108", name: "Dr. A Sravanthi Peddinti", department: "School of Engineering", role: "Faculty" },
  { id: "F109", name: "Dr. Karthik Nasani", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F110", name: "Dr. Idrish Shaik", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F111", name: "Dr. Mogadala Vinod Kumar", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F112", name: "Dr. Gupteswar Sahu", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F113", name: "Ms. Badireddy Satya Sridevi", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F114", name: "Mr. Budaraju Srinivas", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F115", name: "Mr. M S R Sekhar", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F116", name: "Mr. Amaradi Konda Babu", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F117", name: "Mr. Gangu Rama Naidu", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F118", name: "Mr. Murrey Neeladri", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F119", name: "Mr. Talla Srinivasa Rao", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F120", name: "Mr. Peteti Bala Srinivas", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F121", name: "Ms. Katta Pavani", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F122", name: "Ms. Chenna Veera Kiranmayi", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F123", name: "Ms. Ykuntam Yamini Devi", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F124", name: "Ms. S S Vidya Balantrapu", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F125", name: "Ms. Yadhiri Yamini Sri Manogna", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F126", name: "Mr. Kumaranarayana Swamy C", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F127", name: "Mr. Praveen Kumar Bathula", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F128", name: "Mr. Ramoju Bheema Sankaram", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F129", name: "Mr. Pudi Ramesh", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F130", name: "Dr. Miranji Katta", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F131", name: "Dr. Siva Chakra Avinash Bikkina", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F132", name: "Dr. Phani Sridhar Addepalli", department: "Computer Science & Engineering", role: "Assistant Professor & HOD" },
  { id: "F133", name: "Dr. Vinjamuri Venkata Kamesh", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F134", name: "Dr. Chandra Sekhar Kolli", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F135", name: "Mr. Kagithapu Rajendra", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F136", name: "Dr. N Visalakshi", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F137", name: "Dr. Pennada Siva Satya Prasad", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F138", name: "Ms. Chinnari Mrudula Pothula", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F139", name: "Dr. Sripada Rama Sree", department: "University Administration", role: "Pro Vice-Chancellor (Academics)" },
  { id: "F140", name: "Dr. A Vanathi", department: "Freshman Engineering", role: "Associate Dean - Freshman Engineering" },
  { id: "F141", name: "Mr. Nalla Siva Kumar", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F142", name: "Mr. Mylavarapu Kalyan Ram", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F143", name: "Dr. Regella Venkata Satya Lalitha", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F144", name: "Dr. Tatapudi Prabhakara Rao", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F145", name: "Dr. Subba Rao Polamuri", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F146", name: "Dr. Tirukoti Sudha Rani", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F147", name: "Dr. M V B Murali Krishna M", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F148", name: "Ms. Kasichainula Vydehi", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F149", name: "Mr. Marni Srinu", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F150", name: "Mr. Gandhikota Umamahesh", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F151", name: "Mr. Ummidisetti Veera Ramesh", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F152", name: "Mr. Ramesh Kothapalli", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F153", name: "Ms. Rananki Padma Sri", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F154", name: "Ms. Kadiyala Bhavani", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F155", name: "Ms. Kondapalli Syamala Kalyani", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F156", name: "Ms. Janapaneedi Srilakshmi", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F157", name: "Ms. Jyothula Vidya", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F158", name: "Ms. Paramalla Bhuvana Sai", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F159", name: "Ms. Koneti Durga Bhavani", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F160", name: "Ms. Malakala Mani Ratnam", department: "Computer Science & Engineering", role: "Faculty" },
  { id: "F161", name: "Mr. Talluri Hari Babu", department: "School of Computing", role: "Faculty" },
  { id: "F162", name: "Mr. Kalyana Chakravarthi G", department: "School of Computing", role: "Faculty" },
  { id: "F163", name: "Dr. Appawala Jayanathi", department: "School of Computing", role: "Faculty" },
  { id: "F164", name: "Ms. Shaik Vahida", department: "School of Computing", role: "Faculty" },
  { id: "F165", name: "Mr. Mallidi Venkata Ajay Kumar Reddy", department: "School of Computing", role: "Faculty" },
  { id: "F166", name: "Ms. Ponnada Bhargavi", department: "School of Computing", role: "Faculty" },
  { id: "F167", name: "Ms. Ponnada Latha Sree", department: "School of Computing", role: "Faculty" },
  { id: "F168", name: "Ms. Mirthipati Satyavathi", department: "School of Computing", role: "Faculty" },
  { id: "F169", name: "Ms. Satti Pravallika", department: "School of Computing", role: "Faculty" },
  { id: "F170", name: "Dr. Makineedi Raja Babu", department: "School of Computing", role: "Associate Professor & HOD" },
  { id: "F171", name: "Dr. Masina Venkata Rajesh", department: "School of Computing", role: "Associate Dean - School of Computing" },
  { id: "F172", name: "Ms. Karuturi Kavyaramyasree", department: "School of Computing", role: "Faculty" },
  { id: "F173", name: "Mr. Pattabhi Rama Mohan P", department: "School of Computing", role: "Faculty" },
  { id: "F174", name: "Dr. Vikram A", department: "School of Computing", role: "Faculty" },
  { id: "F175", name: "Mr. Soloman Raju Cherukuri", department: "School of Computing", role: "Faculty" },
  { id: "F176", name: "Mr. Chilli Bhanu Prakash", department: "School of Computing", role: "Faculty" },
  { id: "F177", name: "Ms. Parasa Keerthana", department: "School of Computing", role: "Faculty" },
  { id: "F178", name: "Ms. Nalam Durga Prasanna", department: "School of Computing", role: "Faculty" },
  { id: "F179", name: "Ms. Appana Venkata Lalitha Devi", department: "School of Computing", role: "Faculty" },
  { id: "F180", name: "Ms. Bhusarapu Hema Nagamani", department: "School of Computing", role: "Faculty" },
  { id: "F181", name: "Dr. Itha Veeranjaneyulu", department: "School of Computing", role: "Faculty" },
  { id: "F182", name: "Ms. Pediredla Srilatha", department: "School of Computing", role: "Faculty" },
  { id: "F183", name: "Dr. Annemneedi Lakshmana Rao", department: "School of Computing", role: "Faculty" },
  { id: "F184", name: "Dr. Karnam Sreenu", department: "School of Computing", role: "Faculty" },
  { id: "F185", name: "Mr. Antharaju K Chakravarthy", department: "School of Computing", role: "Faculty" },
  { id: "F186", name: "Ms. Sadineni Neelima", department: "School of Computing", role: "Faculty" },
  { id: "F187", name: "Mr. Gunnam Srinivas", department: "School of Computing", role: "Faculty" },
  { id: "F188", name: "Dr. Sunkara Sushma", department: "School of Computing", role: "Faculty" },
  { id: "F189", name: "Mr. Tatapudi S Ramakrishna", department: "School of Computing", role: "Faculty" },
  { id: "F190", name: "Mr. Vadige Sathish Kumar", department: "School of Computing", role: "Faculty" },
  { id: "F191", name: "Ms. Chaliki Archana", department: "Agricultural Engineering", role: "Faculty" },
  { id: "F192", name: "Mr. Chitneedi Kasi Viswanadham", department: "Agricultural Engineering", role: "Faculty" },
  { id: "F193", name: "Ms. Adduri Harika", department: "Agricultural Engineering", role: "Faculty" },
  { id: "F194", name: "Mr. Marisetti Kalyan Ramudu", department: "Agricultural Engineering", role: "Faculty" },
  { id: "F195", name: "Ms. Anyam Giriswari", department: "Agricultural Engineering", role: "Faculty" },
  { id: "F196", name: "Dr. Reminisetty Giri Prasad", department: "Admissions", role: "Associate Dean - Admissions" },
  { id: "F197", name: "Dr. Thandlam Anil Kumar", department: "Agricultural Engineering", role: "Faculty" },
  { id: "F198", name: "Mr. Yalla R S Narayana", department: "Agricultural Engineering", role: "Faculty" },
  { id: "F199", name: "Mr. Vangala V Srimannarayana", department: "Agricultural Engineering", role: "Faculty" },
  { id: "F200", name: "Mr. Chikkam China Subba Rao", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F201", name: "Mr. V V Shankar Anuprakash M", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F202", name: "Mr. Jannela Yernaidu", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F203", name: "Dr. Bodasingi Krishna Kanth", department: "Agricultural Engineering", role: "Assistant Professor & HOD" },
  { id: "F204", name: "Dr. Sundaragiri Rahaman", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F205", name: "Dr. Vedantam Sai Krishna", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F206", name: "Dr. Mude Vinayak", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F207", name: "Dr. Aphia Amulya Palle", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F208", name: "Ms. Gayam Sujatha", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F209", name: "Dr. Budithi Gowtham Singh", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F210", name: "Ms. Rangineni Manasa Lakshmi Durga", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F211", name: "Dr. Kovvuri N Bhargavi", department: "Artificial Intelligence & Machine Learning", role: "Associate Professor & HOD" },
  { id: "F212", name: "Ms. Chinta Sri Divya", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F213", name: "Dr. Maganti Venkatesh", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F214", name: "Dr. Bukke Devaraj Naik", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F215", name: "Dr. Suneetha Racharla", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F216", name: "Dr. Mangalapalli Vamsikrishna", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F217", name: "Dr. Raviteja Vinjamuri", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F218", name: "Mr. Mylavarapu Sarat Chandra Prasad", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F219", name: "Mr. Metla Subrahmanyam", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F220", name: "Dr. Bollu Manikyala Rao", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F221", name: "Dr. Somarapu Ramasubbanna", department: "Artificial Intelligence & Machine Learning", role: "Faculty" },
  { id: "F222", name: "Ms. Nalla Akhila", department: "School of Business", role: "Faculty" },
  { id: "F223", name: "Dr. Kaladi Govindaraju", department: "School of Business", role: "Faculty" },
  { id: "F224", name: "Ms. Alamanda Sophia", department: "School of Business", role: "Faculty" },
  { id: "F225", name: "Dr. G Sanjeeva Rao", department: "Career Development", role: "Dean - Career Development" },
  { id: "F226", name: "Dr. Ramakrishna Reddy Mule", department: "School of Business", role: "Faculty" },
  { id: "F227", name: "Dr. Dasari Veeraswamy", department: "School of Business", role: "Faculty" },
  { id: "F228", name: "Mr. Vengalapudi Appalakonda", department: "School of Business", role: "Faculty" },
  { id: "F229", name: "Mr. P V V S D Nagendrudu", department: "School of Business", role: "Faculty" },
  { id: "F230", name: "Mr. Grandi Sivasankar", department: "School of Business", role: "Faculty" },
  { id: "F231", name: "Ms. Venkata Bala Annapurna P", department: "School of Business", role: "Faculty" },
  { id: "F232", name: "Mr. Showri Rayalu Bandanadam", department: "School of Business", role: "Faculty" },
  { id: "F233", name: "Mr. Mangam Sudheer", department: "School of Business", role: "Faculty" },
  { id: "F234", name: "Dr. Ravi Thangjam", department: "School of Business", role: "Pro-Vice Chancellor (S & P) & Dean (SB)" },
  { id: "F235", name: "Dr. S Md Shakir Ali", department: "Aditya University", role: "Faculty" },
  { id: "F236", name: "Dr. Sowjanya Bagadi", department: "School of Business", role: "Associate Dean - School of Business" },
  { id: "F237", name: "Dr. Kiranmayi C", department: "Aditya University", role: "Faculty" },
  { id: "F238", name: "Dr. Manchala Veera Krishna", department: "Aditya University", role: "Faculty" },
  { id: "F239", name: "Dr. Ganta Satyanarayana", department: "Aditya University", role: "Faculty" },
  { id: "F240", name: "Dr. Durga Prasad Tapeswarapu", department: "Aditya University", role: "Faculty" },
  { id: "F241", name: "Dr. Sreerama Raju Malladi", department: "Aditya University", role: "Faculty" },
  { id: "F242", name: "Dr. Suresh Talamala", department: "Aditya University", role: "Faculty" },
  { id: "F243", name: "Dr. Koka Shailaja Rao", department: "Aditya University", role: "Faculty" },
];
module.exports.length = 243;

