// Food & campus shop master data from Aditya_Surampalem_Complete_Food_and_Shops_List.docx
// Each shop: { name, area, group, items: [{ name, price }] }. Prices are display strings
// (may be "₹100", "₹10–30", "Varies by day", etc.).
module.exports = [
  {
    name: "Pencil Canteen",
    area: "Main Campus",
    group: null,
    items: [
      { name: "Fried Rice", price: "₹100" },
      { name: "Noodles", price: "₹90" },
      { name: "Biryani", price: "₹150" },
      { name: "Maggi", price: "₹50" },
      { name: "Chapathi", price: "₹70" },
      { name: "Parota", price: "₹100" },
      { name: "Cool Drinks & Packed Juices", price: "₹10–30" },
      { name: "Ice Creams", price: "₹10–50" },
      { name: "Biscuit Packets", price: "₹10–50" },
      { name: "Chocolates", price: "₹1–100" },
      { name: "Lays / Kurkure", price: "₹10–30" },
      { name: "Samosa", price: "₹20" },
      { name: "Vada", price: "₹20" },
      { name: "Pani Puri", price: "₹30" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
      { name: "Falooda", price: "₹60" },
      { name: "Cream Bun", price: "₹20" },
      { name: "Sandwich", price: "₹70" },
      { name: "Veg Roll", price: "₹60" },
    ],
  },
  {
    name: "Satya Canteen",
    area: "Main Campus",
    group: null,
    items: [
      { name: "Fried Rice", price: "₹100" },
      { name: "Noodles", price: "₹90" },
      { name: "Biryani", price: "₹150" },
      { name: "Chapathi", price: "₹70" },
      { name: "Parota", price: "₹100" },
      { name: "Cool Drinks & Packed Juices", price: "₹10–30" },
    ],
  },
  {
    name: "Ball Canteen 1",
    area: "Main Campus",
    group: null,
    items: [
      { name: "Cool Drinks & Packed Juices", price: "₹10–30" },
      { name: "Ice Creams", price: "₹10–50" },
      { name: "Biscuit Packets", price: "₹10–50" },
      { name: "Chocolates", price: "₹1–100" },
      { name: "Lays / Kurkure", price: "₹10–30" },
      { name: "Samosa", price: "₹20" },
      { name: "Vada", price: "₹20" },
      { name: "Pani Puri", price: "₹30" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
      { name: "Maggi", price: "₹50" },
      { name: "Sandwich", price: "₹70" },
    ],
  },
  {
    name: "Eat n Play 1",
    area: "Main Campus",
    group: null,
    items: [
      { name: "Cool Drinks & Packed Juices", price: "₹10–30" },
      { name: "Ice Creams", price: "₹10–50" },
      { name: "Biscuit Packets", price: "₹10–50" },
      { name: "Chocolates", price: "₹1–100" },
      { name: "Lays / Kurkure", price: "₹10–30" },
      { name: "Samosa", price: "₹20" },
      { name: "Vada", price: "₹20" },
      { name: "Pani Puri", price: "₹30" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
      { name: "Maggi", price: "₹50" },
      { name: "Sandwich", price: "₹70" },
    ],
  },
  {
    name: "Speed Copy",
    area: "Main Campus",
    group: null,
    items: [
      { name: "B/W Xerox", price: "₹1–2/page" },
      { name: "Colour Print", price: "₹5–15/page" },
      { name: "B/W Print", price: "₹1–3/page" },
      { name: "Scanning", price: "₹5–20" },
      { name: "Spiral Binding", price: "₹30–80" },
      { name: "Soft Binding", price: "₹50–120" },
      { name: "Project Printing", price: "₹30–200+" },
      { name: "Record Printing", price: "₹30–150" },
      { name: "Resume Printing", price: "₹10–30" },
      { name: "ID / Card Print", price: "₹10–30" },
      { name: "Photo Print", price: "₹10–50" },
      { name: "Lamination", price: "₹10–50" },
      { name: "Document Photocopy", price: "₹1–2/page" },
      { name: "Assignment Printing", price: "₹10–100+" },
      { name: "File / Document Binding", price: "₹30–100" },
    ],
  },
  {
    name: "Bakery",
    area: "Main Campus",
    group: null,
    items: [
      { name: "Fruit Juices", price: "₹50–100" },
      { name: "Milkshakes", price: "₹70–130" },
      { name: "Cakes", price: "₹30–100" },
      { name: "Chocolates", price: "₹10–300" },
      { name: "Cool Drinks", price: "Varies" },
      { name: "Ice Creams", price: "₹10–50" },
      { name: "Cream Bun", price: "₹20" },
    ],
  },
  {
    name: "Eat n Play 2",
    area: "Main Campus",
    group: null,
    items: [
      { name: "Cool Drinks & Packed Juices", price: "₹10–30" },
      { name: "Ice Creams", price: "₹10–50" },
      { name: "Biscuit Packets", price: "₹10–50" },
      { name: "Chocolates", price: "₹1–100" },
      { name: "Lays / Kurkure", price: "₹10–30" },
      { name: "Samosa", price: "₹20" },
      { name: "Vada", price: "₹20" },
      { name: "Pani Puri", price: "₹30" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
      { name: "Maggi", price: "₹50" },
      { name: "Sandwich", price: "₹70" },
    ],
  },
  {
    name: "Kitchen",
    area: "Main Campus",
    group: null,
    items: [
      { name: "Fried Rice", price: "₹100" },
      { name: "Noodles", price: "₹90" },
      { name: "Biryani", price: "₹150" },
      { name: "Chapathi", price: "₹70" },
      { name: "Parota", price: "₹100" },
      { name: "Cool Drinks & Packed Juices", price: "₹10–30" },
      { name: "Ice Creams", price: "₹10–50" },
      { name: "Biscuit Packets", price: "₹10–50" },
      { name: "Chocolates", price: "₹1–100" },
      { name: "Lays / Kurkure", price: "₹10–30" },
      { name: "Samosa", price: "₹20" },
      { name: "Vada", price: "₹20" },
      { name: "Sandwich", price: "₹70" },
      { name: "Veg Roll", price: "₹60" },
    ],
  },
  {
    name: "Xerox Shop",
    area: "Main Campus",
    group: null,
    items: [
      { name: "B/W Xerox", price: "₹1–2/page" },
      { name: "Colour Print", price: "₹5–15/page" },
      { name: "B/W Print", price: "₹1–3/page" },
      { name: "Scanning", price: "₹5–20" },
      { name: "Spiral Binding", price: "₹30–80" },
      { name: "Lamination", price: "₹10–50" },
      { name: "Document Photocopy", price: "₹1–2/page" },
    ],
  },
  {
    name: "Book Shop",
    area: "Main Campus",
    group: null,
    items: [
      { name: "Notebook", price: "₹30–100" },
      { name: "Record Book", price: "₹30–100" },
      { name: "Lab Record", price: "₹40–100" },
      { name: "Practical Record", price: "₹40–100" },
      { name: "Pen", price: "₹5–30" },
      { name: "Pencil", price: "₹5–15" },
      { name: "Eraser", price: "₹5–10" },
      { name: "Scale", price: "₹10–30" },
      { name: "Marker", price: "₹20–50" },
      { name: "File / Folder", price: "₹20–80" },
      { name: "A4 Sheets", price: "₹1–5/sheet" },
      { name: "Drawing Sheets", price: "₹5–15" },
      { name: "Project File", price: "₹20–60" },
      { name: "Text / Reference Books", price: "Varies" },
    ],
  },
  {
    name: "Ball Canteen 2",
    area: "Main Campus",
    group: null,
    items: [
      { name: "Cool Drinks & Packed Juices", price: "₹10–30" },
      { name: "Ice Creams", price: "₹10–50" },
      { name: "Biscuit Packets", price: "₹10–50" },
      { name: "Chocolates", price: "₹1–100" },
      { name: "Lays / Kurkure", price: "₹10–30" },
      { name: "Samosa", price: "₹20" },
      { name: "Vada", price: "₹20" },
      { name: "Pani Puri", price: "₹30" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
      { name: "Maggi", price: "₹50" },
      { name: "Sandwich", price: "₹70" },
    ],
  },
  {
    name: "Sri Sai Aditya Canteen",
    area: "Main Campus",
    group: null,
    items: [
      { name: "Cool Drinks & Packed Juices", price: "₹10–30" },
      { name: "Ice Creams", price: "₹10–50" },
      { name: "Biscuit Packets", price: "₹10–50" },
      { name: "Chocolates", price: "₹1–100" },
      { name: "Lays / Kurkure", price: "₹10–30" },
      { name: "Samosa", price: "₹20" },
      { name: "Vada", price: "₹20" },
      { name: "Pani Puri", price: "₹30" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
      { name: "Maggi", price: "₹50" },
      { name: "Sandwich", price: "₹70" },
    ],
  },
  {
    name: "RK Canteen",
    area: "Main Campus",
    group: null,
    items: [
      { name: "Cool Drinks & Packed Juices", price: "₹10–30" },
      { name: "Ice Creams", price: "₹10–50" },
      { name: "Biscuit Packets", price: "₹10–50" },
      { name: "Chocolates", price: "₹1–100" },
      { name: "Lays / Kurkure", price: "₹10–30" },
      { name: "Samosa", price: "₹20" },
      { name: "Vada", price: "₹20" },
      { name: "Pani Puri", price: "₹30" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
      { name: "Maggi", price: "₹50" },
      { name: "Sandwich", price: "₹70" },
    ],
  },
  {
    name: "Street Food Stall 1",
    area: "Main Campus",
    group: "Street Food Stalls",
    items: [
      { name: "Pani Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
      { name: "Falooda", price: "₹60" },
      { name: "Ice Cream", price: "₹20" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Samosa", price: "₹20" },
      { name: "Noodles", price: "₹60 / ₹100" },
    ],
  },
  {
    name: "Street Food Stall 2",
    area: "Main Campus",
    group: "Street Food Stalls",
    items: [
      { name: "Pani Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
      { name: "Falooda", price: "₹60" },
      { name: "Ice Cream", price: "₹20" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Samosa", price: "₹20" },
      { name: "Noodles", price: "₹60 / ₹100" },
    ],
  },
  {
    name: "Street Food Stall 3",
    area: "Main Campus",
    group: "Street Food Stalls",
    items: [
      { name: "Pani Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
      { name: "Falooda", price: "₹60" },
      { name: "Ice Cream", price: "₹20" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Samosa", price: "₹20" },
      { name: "Noodles", price: "₹60 / ₹100" },
    ],
  },
  {
    name: "Street Food Stall 4",
    area: "Main Campus",
    group: "Street Food Stalls",
    items: [
      { name: "Pani Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
      { name: "Falooda", price: "₹60" },
      { name: "Ice Cream", price: "₹20" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Samosa", price: "₹20" },
      { name: "Noodles", price: "₹60 / ₹100" },
    ],
  },
  {
    name: "Eat n Play Canteen",
    area: "Girls Hostel",
    group: null,
    items: [
      { name: "Fried Rice", price: "₹100" },
      { name: "Noodles", price: "₹90" },
      { name: "Biryani", price: "₹150" },
      { name: "Chapathi", price: "₹70" },
      { name: "Parota", price: "₹100" },
      { name: "Cool Drinks & Packed Juices", price: "₹10–30" },
      { name: "Ice Creams", price: "₹10–50" },
      { name: "Biscuit Packets", price: "₹10–50" },
      { name: "Chocolates", price: "₹1–100" },
      { name: "Lays / Kurkure", price: "₹10–30" },
      { name: "Samosa", price: "₹20" },
      { name: "Vada", price: "₹20" },
      { name: "Pani Puri", price: "₹30" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
      { name: "Maggi", price: "₹50" },
      { name: "Sandwich", price: "₹70" },
    ],
  },
  {
    name: "Girls Hostel Mess — Blocks A & B",
    area: "Girls Hostel",
    group: "Girls Hostel Messes",
    items: [
      { name: "Dosa", price: "Varies by day" },
      { name: "Vada", price: "Varies by day" },
      { name: "Upma", price: "Varies by day" },
      { name: "Sambar", price: "Varies by day" },
      { name: "Chutney", price: "Varies by day" },
      { name: "Uthappam", price: "Varies by day" },
      { name: "Bonda", price: "Varies by day" },
      { name: "Chapathi", price: "Varies by day" },
      { name: "Egg & Bread", price: "Daily" },
      { name: "Rice", price: "Daily" },
      { name: "Curries", price: "Varies by day" },
      { name: "Curd", price: "Varies by day" },
      { name: "Pani Puri", price: "Varies" },
      { name: "Noodles", price: "Varies" },
      { name: "Cream Bun", price: "Varies" },
      { name: "Biryani", price: "Sometimes" },
    ],
  },
  {
    name: "Girls Hostel Mess — Blocks C & D",
    area: "Girls Hostel",
    group: "Girls Hostel Messes",
    items: [
      { name: "Dosa", price: "Varies by day" },
      { name: "Vada", price: "Varies by day" },
      { name: "Upma", price: "Varies by day" },
      { name: "Sambar", price: "Varies by day" },
      { name: "Chutney", price: "Varies by day" },
      { name: "Uthappam", price: "Varies by day" },
      { name: "Bonda", price: "Varies by day" },
      { name: "Chapathi", price: "Varies by day" },
      { name: "Egg & Bread", price: "Daily" },
      { name: "Rice", price: "Daily" },
      { name: "Curries", price: "Varies by day" },
      { name: "Curd", price: "Varies by day" },
      { name: "Pani Puri", price: "Varies" },
      { name: "Noodles", price: "Varies" },
      { name: "Cream Bun", price: "Varies" },
      { name: "Biryani", price: "Sometimes" },
    ],
  },
  {
    name: "Girls Hostel Mess — Blocks E & F",
    area: "Girls Hostel",
    group: "Girls Hostel Messes",
    items: [
      { name: "Dosa", price: "Varies by day" },
      { name: "Vada", price: "Varies by day" },
      { name: "Upma", price: "Varies by day" },
      { name: "Sambar", price: "Varies by day" },
      { name: "Chutney", price: "Varies by day" },
      { name: "Uthappam", price: "Varies by day" },
      { name: "Bonda", price: "Varies by day" },
      { name: "Chapathi", price: "Varies by day" },
      { name: "Egg & Bread", price: "Daily" },
      { name: "Rice", price: "Daily" },
      { name: "Curries", price: "Varies by day" },
      { name: "Curd", price: "Varies by day" },
      { name: "Pani Puri", price: "Varies" },
      { name: "Noodles", price: "Varies" },
      { name: "Cream Bun", price: "Varies" },
      { name: "Biryani", price: "Sometimes" },
    ],
  },
  {
    name: "Boys Hostel Mess — Block 5",
    area: "Boys Hostel",
    group: null,
    items: [
      { name: "Dosa", price: "Varies by day" },
      { name: "Vada", price: "Varies by day" },
      { name: "Upma", price: "Varies by day" },
      { name: "Sambar", price: "Varies by day" },
      { name: "Chutney", price: "Varies by day" },
      { name: "Uthappam", price: "Varies by day" },
      { name: "Bonda", price: "Varies by day" },
      { name: "Chapathi", price: "Varies by day" },
      { name: "Egg & Bread", price: "Daily" },
      { name: "Rice", price: "Daily" },
      { name: "Curries", price: "Varies by day" },
      { name: "Curd", price: "Varies by day" },
      { name: "Pani Puri", price: "Varies" },
      { name: "Noodles", price: "Varies" },
      { name: "Cream Bun", price: "Varies" },
      { name: "Biryani", price: "Sometimes" },
    ],
  },
  {
    name: "Boys Hostel Mess — Block 4",
    area: "Boys Hostel",
    group: null,
    items: [
      { name: "Dosa", price: "Varies by day" },
      { name: "Vada", price: "Varies by day" },
      { name: "Upma", price: "Varies by day" },
      { name: "Sambar", price: "Varies by day" },
      { name: "Chutney", price: "Varies by day" },
      { name: "Uthappam", price: "Varies by day" },
      { name: "Bonda", price: "Varies by day" },
      { name: "Chapathi", price: "Varies by day" },
      { name: "Egg & Bread", price: "Daily" },
      { name: "Rice", price: "Daily" },
      { name: "Curries", price: "Varies by day" },
      { name: "Curd", price: "Varies by day" },
      { name: "Pani Puri", price: "Varies" },
      { name: "Noodles", price: "Varies" },
      { name: "Cream Bun", price: "Varies" },
      { name: "Biryani", price: "Sometimes" },
    ],
  },
  {
    name: "Boys Hostel Mess — Block 3",
    area: "Boys Hostel",
    group: null,
    items: [
      { name: "Dosa", price: "Varies by day" },
      { name: "Vada", price: "Varies by day" },
      { name: "Upma", price: "Varies by day" },
      { name: "Sambar", price: "Varies by day" },
      { name: "Chutney", price: "Varies by day" },
      { name: "Uthappam", price: "Varies by day" },
      { name: "Bonda", price: "Varies by day" },
      { name: "Chapathi", price: "Varies by day" },
      { name: "Egg & Bread", price: "Daily" },
      { name: "Rice", price: "Daily" },
      { name: "Curries", price: "Varies by day" },
      { name: "Curd", price: "Varies by day" },
      { name: "Pani Puri", price: "Varies" },
      { name: "Noodles", price: "Varies" },
      { name: "Cream Bun", price: "Varies" },
      { name: "Biryani", price: "Sometimes" },
    ],
  },
  {
    name: "Boys Hostel Mess — Block 2",
    area: "Boys Hostel",
    group: null,
    items: [
      { name: "Dosa", price: "Varies by day" },
      { name: "Vada", price: "Varies by day" },
      { name: "Upma", price: "Varies by day" },
      { name: "Sambar", price: "Varies by day" },
      { name: "Chutney", price: "Varies by day" },
      { name: "Uthappam", price: "Varies by day" },
      { name: "Bonda", price: "Varies by day" },
      { name: "Chapathi", price: "Varies by day" },
      { name: "Egg & Bread", price: "Daily" },
      { name: "Rice", price: "Daily" },
      { name: "Curries", price: "Varies by day" },
      { name: "Curd", price: "Varies by day" },
      { name: "Pani Puri", price: "Varies" },
      { name: "Noodles", price: "Varies" },
      { name: "Cream Bun", price: "Varies" },
      { name: "Biryani", price: "Sometimes" },
    ],
  },
  {
    name: "Boys Hostel Mess — Block 1",
    area: "Boys Hostel",
    group: null,
    items: [
      { name: "Dosa", price: "Varies by day" },
      { name: "Vada", price: "Varies by day" },
      { name: "Upma", price: "Varies by day" },
      { name: "Sambar", price: "Varies by day" },
      { name: "Chutney", price: "Varies by day" },
      { name: "Uthappam", price: "Varies by day" },
      { name: "Bonda", price: "Varies by day" },
      { name: "Chapathi", price: "Varies by day" },
      { name: "Egg & Bread", price: "Daily" },
      { name: "Rice", price: "Daily" },
      { name: "Curries", price: "Varies by day" },
      { name: "Curd", price: "Varies by day" },
      { name: "Pani Puri", price: "Varies" },
      { name: "Noodles", price: "Varies" },
      { name: "Cream Bun", price: "Varies" },
      { name: "Biryani", price: "Sometimes" },
    ],
  },
  {
    name: "Boys Hostel Canteen",
    area: "Boys Hostel",
    group: null,
    items: [
      { name: "Fried Rice", price: "₹100" },
      { name: "Noodles", price: "₹90" },
      { name: "Biryani", price: "₹150" },
      { name: "Chapathi", price: "₹70" },
      { name: "Parota", price: "₹100" },
      { name: "Cool Drinks & Packed Juices", price: "₹10–30" },
      { name: "Ice Creams", price: "₹10–50" },
      { name: "Biscuit Packets", price: "₹10–50" },
      { name: "Chocolates", price: "₹1–100" },
      { name: "Lays / Kurkure", price: "₹10–30" },
      { name: "Samosa", price: "₹20" },
      { name: "Vada", price: "₹20" },
      { name: "Maggi", price: "₹50" },
      { name: "Pani Puri", price: "₹30" },
      { name: "Masala Puri", price: "₹30" },
      { name: "Manchuria", price: "₹50" },
    ],
  },
  {
    name: "Boys Hostel Vending Machine",
    area: "Boys Hostel",
    group: null,
    items: [
      { name: "Cool Drinks", price: "₹10–30" },
      { name: "Packed Juices", price: "₹10–30" },
      { name: "Biscuits", price: "₹10–50" },
      { name: "Chocolates", price: "₹1–100" },
      { name: "Lays / Kurkure", price: "₹10–30" },
      { name: "Water Bottle", price: "₹25" },
    ],
  },
  {
    name: "Faculty Block Mess",
    area: "Faculty Block",
    group: null,
    items: [
      { name: "Dosa", price: "Varies by day" },
      { name: "Vada", price: "Varies by day" },
      { name: "Upma", price: "Varies by day" },
      { name: "Sambar", price: "Varies by day" },
      { name: "Chutney", price: "Varies by day" },
      { name: "Uthappam", price: "Varies by day" },
      { name: "Bonda", price: "Varies by day" },
      { name: "Chapathi", price: "Varies by day" },
      { name: "Egg & Bread", price: "Daily" },
      { name: "Rice", price: "Daily" },
      { name: "Curries", price: "Varies by day" },
      { name: "Curd", price: "Varies by day" },
      { name: "Pani Puri", price: "Varies" },
      { name: "Noodles", price: "Varies" },
      { name: "Cream Bun", price: "Varies" },
      { name: "Biryani", price: "Sometimes" },
    ],
  },
];
module.exports.length = 29;