require("dotenv").config();
const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const connectDB = require("../config/db");

const Department = require("../models/Department");
const Faculty = require("../models/Faculty");
const PointOfInterest = require("../models/PointOfInterest");
const BusRoute = require("../models/BusRoute");
const Event = require("../models/Event");
const QueryLog = require("../models/QueryLog");

async function seed() {
  await connectDB();

  await Promise.all([
    Department.deleteMany({}),
    Faculty.deleteMany({}),
    PointOfInterest.deleteMany({}),
    BusRoute.deleteMany({}),
    Event.deleteMany({}),
    QueryLog.deleteMany({}),
  ]);

  const departments = await Department.insertMany([
    {
      name: "Computer Science & Engineering",
      code: "CSE",
      block: "Ramanujan Bhavan",
      floor: "1st Floor",
      hod: "Dr. K. Ayyappa Swamy",
      labs: [
        "Database Management Systems Lab",
        "Computer Networks Lab",
        "Software Engineering Lab",
        "Operating Systems Lab",
      ],
      contactEmail: "cse@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Information Technology",
      code: "IT",
      block: "Newton Bhavan",
      floor: "2nd Floor",
      hod: "Dr. P. Surya Lakshmi",
      labs: ["Web Technologies Lab", "Cloud Computing Lab", "Data Structures Lab"],
      contactEmail: "it@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Artificial Intelligence & Machine Learning",
      code: "AIML",
      block: "James Watt Bhavan",
      floor: "Ground Floor",
      hod: "Dr. S. Satyanarayana",
      labs: ["AI Lab", "Machine Learning Lab", "Deep Learning Lab"],
      contactEmail: "aiml@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Artificial Intelligence & Data Science",
      code: "AI&DS",
      block: "James Watt Bhavan",
      floor: "1st Floor",
      hod: "Dr. K. Sridevi",
      labs: ["Data Science Lab", "Big Data Analytics Lab", "AI & Robotics Lab"],
      contactEmail: "aids@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Electronics & Communication Engineering",
      code: "ECE",
      block: "Visvesvaraya Bhavan",
      floor: "Ground Floor",
      hod: "Dr. G. Sridevi",
      labs: ["VLSI Design Lab", "Embedded Systems Lab", "Signals & Systems Lab", "RF & Microwave Lab"],
      contactEmail: "ece@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Electrical & Electronics Engineering",
      code: "EEE",
      block: "C.V. Raman Bhavan",
      floor: "1st Floor",
      hod: "Dr. S. H. V. S. Prasad",
      labs: ["Electrical Machines Lab", "Power Systems Lab", "Control Systems Lab"],
      contactEmail: "eee@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Mechanical Engineering",
      code: "ME",
      block: "C.V. Raman Bhavan",
      floor: "Ground Floor",
      hod: "Dr. G. Sanjeev Rao",
      labs: ["Thermal Engineering Lab", "CAD/CAM Lab", "Fluid Mechanics Lab", "Workshop"],
      contactEmail: "me@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Civil Engineering",
      code: "CE",
      block: "C.V. Raman Bhavan",
      floor: "2nd Floor",
      hod: "Dr. P. N. V. L. Prasad",
      labs: ["Concrete Tech Lab", "Surveying Lab", "Geotech Lab", "Environmental Lab"],
      contactEmail: "ce@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Mining Engineering",
      code: "MIN",
      block: "Cotton Bhavan",
      floor: "Ground Floor",
      hod: "Dr. B. Ravi Kumar",
      labs: ["Mine Surveying Lab", "Mining Machinery Lab", "Rock Mechanics Lab"],
      contactEmail: "mining@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Petroleum Technology",
      code: "PET",
      block: "Ratan Tata Bhavan",
      floor: "1st Floor",
      hod: "Dr. M. V. Rao",
      labs: ["Drilling Fluids Lab", "Petroleum Reservoir Lab", "Production Operations Lab"],
      contactEmail: "petroleum@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Agricultural Engineering",
      code: "AG",
      block: "Cotton Bhavan",
      floor: "1st Floor",
      hod: "Dr. N. Samba Siva Rao",
      labs: ["Soil Science Lab", "Farm Machinery Lab", "Irrigation Engineering Lab"],
      contactEmail: "agri@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Computer Applications (BCA)",
      code: "BCA",
      block: "Bill Gates Bhavan",
      floor: "Ground Floor",
      hod: "Dr. P. Bala Krishna",
      labs: ["Programming Lab", "Web Development Lab"],
      contactEmail: "bca@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Computer Applications (MCA)",
      code: "MCA",
      block: "Aditya Degree & PG College",
      floor: "Ground Floor",
      hod: "Dr. M. Venkateswara Rajesh",
      labs: ["Programming Lab", "Placement Practice Lab"],
      contactEmail: "mca@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "Business Administration",
      code: "MBA",
      block: "Aditya Degree & PG College",
      floor: "1st Floor",
      hod: "Dr. Sowjanya Bagadi",
      labs: ["Business Analytics Lab", "Case Study Room"],
      contactEmail: "mba@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "School of Sciences",
      code: "SCI",
      block: "Aditya Degree & PG College",
      floor: "2nd Floor",
      hod: "Mr. V. Anil Chavan",
      labs: ["Forensic Science Lab", "Cyber Security Lab", "Life Sciences Lab"],
      contactEmail: "sciences@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
    {
      name: "School of Pharmacy",
      code: "PHA",
      block: "Aditya Pharmacy College",
      floor: "Ground Floor",
      hod: "Dr. D. Sathis Kumar",
      labs: ["Pharmaceutical Chemistry Lab", "Pharmacognosy Lab", "Pharmacology Lab"],
      contactEmail: "pharmacy@adityauniversity.in",
      officeHours: "9:00 AM - 6:00 PM",
    },
  ]);

  await Faculty.insertMany([
    {
      name: "Dr. G. Sridevi",
      departmentId: departments[4]._id,
      departmentName: "ECE",
      designation: "Professor & Dean, School of Engineering",
      cabin: "V102",
      block: "Visvesvaraya Bhavan",
      floor: "Ground Floor",
      email: "gsridevi@adityauniversity.in",
      subjects: ["VLSI Design", "Digital Electronics"],
      onLeave: false,
      availableSlots: ["10:00-11:00 AM", "3:00-4:00 PM"],
    },
    {
      name: "Dr. M. Venkateswara Rajesh",
      departmentId: departments[12]._id,
      departmentName: "MCA",
      designation: "Professor & Associate Dean, School of Computing",
      cabin: "DGC101",
      block: "Aditya Degree & PG College",
      floor: "Ground Floor",
      email: "mvrajesh@adityauniversity.in",
      subjects: ["Data Structures", "Algorithms"],
      onLeave: false,
      availableSlots: ["11:00 AM-12:00 PM"],
    },
    {
      name: "Dr. Sowjanya Bagadi",
      departmentId: departments[13]._id,
      departmentName: "MBA",
      designation: "Associate Professor & Associate Dean, School of Business",
      cabin: "DGC210",
      block: "Aditya Degree & PG College",
      floor: "1st Floor",
      email: "sowjanya.bagadi@adityauniversity.in",
      subjects: ["Marketing Management", "Financial Accounting"],
      onLeave: false,
      availableSlots: ["2:00-3:00 PM"],
    },
    {
      name: "Mr. V. Anil Chavan",
      departmentId: departments[14]._id,
      departmentName: "SCI",
      designation: "Assistant Professor & Associate Dean, School of Sciences",
      cabin: "DGC302",
      block: "Aditya Degree & PG College",
      floor: "2nd Floor",
      email: "anilchavan@adityauniversity.in",
      subjects: ["Cyber Security", "Forensic Science"],
      onLeave: false,
      availableSlots: ["10:00-11:00 AM"],
    },
    {
      name: "Dr. D. Sathis Kumar",
      departmentId: departments[15]._id,
      departmentName: "PHA",
      designation: "Professor & Dean, School of Pharmacy",
      cabin: "APC130",
      block: "Aditya Pharmacy College",
      floor: "Ground Floor",
      email: "sathiskumar@adityauniversity.in",
      subjects: ["Pharmaceutical Chemistry"],
      onLeave: false,
      availableSlots: ["4:00-5:00 PM"],
    },
    {
      name: "Dr. K. Ayyappa Swamy",
      departmentId: departments[0]._id,
      departmentName: "CSE",
      designation: "Professor & Associate Dean - Academics",
      cabin: "R203",
      block: "Ramanujan Bhavan",
      floor: "1st Floor",
      email: "ayyappaswamy@adityauniversity.in",
      subjects: ["DBMS", "Software Engineering"],
      onLeave: false,
      availableSlots: ["9:00-10:00 AM", "2:00-3:00 PM"],
    },
    {
      name: "Dr. S. Satyanarayana",
      departmentId: departments[2]._id,
      departmentName: "AIML",
      designation: "Professor & HOD, AIML",
      cabin: "JW031",
      block: "James Watt Bhavan",
      floor: "Ground Floor",
      email: "satyanarayana@adityauniversity.in",
      subjects: ["Machine Learning", "Deep Learning"],
      onLeave: false,
      availableSlots: ["11:00 AM-12:00 PM", "4:00-5:00 PM"],
    },
    {
      name: "Dr. B. Ravi Kumar",
      departmentId: departments[8]._id,
      departmentName: "MIN",
      designation: "Professor & HOD, Mining",
      cabin: "CT014",
      block: "Cotton Bhavan",
      floor: "Ground Floor",
      email: "ravikumar.mining@adityauniversity.in",
      subjects: ["Mine Ventilation", "Surface Mining"],
      onLeave: false,
      availableSlots: ["10:00-11:00 AM"],
    },
    {
      name: "Dr. P. Surya Lakshmi",
      departmentId: departments[1]._id,
      departmentName: "IT",
      designation: "Associate Professor & HOD, IT",
      cabin: "NW311",
      block: "Newton Bhavan",
      floor: "2nd Floor",
      email: "psuryalakshmi@adityauniversity.in",
      subjects: ["Cloud Computing", "Web Technologies"],
      onLeave: true,
      availableSlots: [],
    },
    {
      name: "Dr. G. Sanjeev Rao",
      departmentId: departments[6]._id,
      departmentName: "ME",
      designation: "Professor & Dean, Career Development",
      cabin: "CV102",
      block: "C.V. Raman Bhavan",
      floor: "Ground Floor",
      email: "sanjeevrao@adityauniversity.in",
      subjects: ["Thermal Engineering", "Engineering Drawing"],
      onLeave: false,
      availableSlots: ["3:00-4:00 PM"],
    },
    {
      name: "Dr. Gandikota Ramu",
      departmentId: departments[0]._id,
      departmentName: "CSE",
      designation: "Professor & Dean, Technical Training",
      cabin: "R207",
      block: "Ramanujan Bhavan",
      floor: "1st Floor",
      email: "gandikotaramu@adityauniversity.in",
      subjects: ["Operating Systems", "Computer Networks"],
      onLeave: false,
      availableSlots: ["12:00-1:00 PM"],
    },
    {
      name: "Dr. D. Kishore",
      departmentId: departments[5]._id,
      departmentName: "EEE",
      designation: "Professor & Dean, Student Activities",
      cabin: "CV205",
      block: "C.V. Raman Bhavan",
      floor: "1st Floor",
      email: "kishore.eee@adityauniversity.in",
      subjects: ["Electrical Machines", "Power Systems"],
      onLeave: false,
      availableSlots: ["9:00-10:00 AM"],
    },
    {
      name: "Dr. A. Vanathi",
      departmentId: departments[4]._id,
      departmentName: "ECE",
      designation: "Associate Professor & Associate Dean, Freshman Engineering",
      cabin: "V115",
      block: "Visvesvaraya Bhavan",
      floor: "Ground Floor",
      email: "vanathi@adityauniversity.in",
      subjects: ["Engineering Physics", "Basic Electronics"],
      onLeave: false,
      availableSlots: ["2:00-3:00 PM"],
    },
    {
      name: "Dr. S. H. V. S. Prasad",
      departmentId: departments[5]._id,
      departmentName: "EEE",
      designation: "Associate Professor & HOD, EEE",
      cabin: "CV210",
      block: "C.V. Raman Bhavan",
      floor: "1st Floor",
      email: "prasad.eee@adityauniversity.in",
      subjects: ["Control Systems", "Power Electronics"],
      onLeave: false,
      availableSlots: ["10:00-11:00 AM"],
    },
  ]);

  // Faculty self-service login: every seeded faculty logs in with their email
  // and this shared demo password. Some also get a timetable so the free-time
  // detection has real data to derive from.
  const FAC_PASSWORD = "faculty123";

  const sampleTimetables = {
    "ayyappaswamy@adityauniversity.in": {
      Monday: [
        { start: "09:00", end: "10:00", subject: "DBMS", room: "R101" },
        { start: "10:00", end: "11:00", subject: "Software Engineering", room: "R101" },
      ],
      Tuesday: [
        { start: "09:00", end: "10:00", subject: "DBMS", room: "R201" },
        { start: "11:00", end: "12:00", subject: "DBMS Lab", room: "DBMS Lab" },
      ],
      Wednesday: [{ start: "09:00", end: "10:00", subject: "Operating Systems", room: "R301" }],
      Thursday: [{ start: "10:00", end: "11:00", subject: "Software Engineering", room: "R101" }],
      Friday: [{ start: "09:00", end: "10:00", subject: "DBMS", room: "R101" }],
    },
    "gandikotaramu@adityauniversity.in": {
      Monday: [
        { start: "10:00", end: "11:00", subject: "Computer Networks", room: "R102" },
        { start: "11:00", end: "12:00", subject: "Computer Networks Lab", room: "CN Lab" },
      ],
      Tuesday: [{ start: "09:00", end: "10:00", subject: "Operating Systems", room: "R102" }],
      Wednesday: [{ start: "10:00", end: "11:00", subject: "Computer Networks", room: "R202" }],
      Thursday: [{ start: "11:00", end: "12:00", subject: "Operating Systems Lab", room: "OS Lab" }],
      Friday: [{ start: "10:00", end: "11:00", subject: "Computer Networks", room: "R102" }],
    },
    "gsridevi@adityauniversity.in": {
      Monday: [
        { start: "09:00", end: "10:00", subject: "VLSI Design", room: "V101" },
        { start: "10:00", end: "11:00", subject: "VLSI Design", room: "V101" },
      ],
      Tuesday: [{ start: "11:00", end: "12:00", subject: "Digital Electronics", room: "V201" }],
      Wednesday: [{ start: "09:00", end: "10:00", subject: "Digital Electronics", room: "V201" }],
      Thursday: [{ start: "10:00", end: "11:00", subject: "VLSI Lab", room: "VLSI Lab" }],
      Friday: [{ start: "02:00", end: "03:00", subject: "VLSI Design", room: "V101" }],
    },
    "sanjeevrao@adityauniversity.in": {
      Monday: [{ start: "09:00", end: "10:00", subject: "Engineering Drawing", room: "CV110" }],
      Tuesday: [{ start: "10:00", end: "11:00", subject: "Thermal Engineering", room: "CV210" }],
      Wednesday: [{ start: "02:00", end: "03:00", subject: "CAD/CAM Lab", room: "CAD Lab" }],
      Thursday: [{ start: "09:00", end: "10:00", subject: "Engineering Drawing", room: "CV110" }],
    },
    "satyanarayana@adityauniversity.in": {
      Monday: [{ start: "09:00", end: "10:00", subject: "Machine Learning", room: "JW101" }],
      Tuesday: [
        { start: "09:00", end: "10:00", subject: "Machine Learning", room: "JW201" },
        { start: "02:00", end: "03:00", subject: "ML Lab", room: "ML Lab" },
      ],
      Wednesday: [{ start: "10:00", end: "11:00", subject: "Deep Learning", room: "JW101" }],
      Thursday: [{ start: "11:00", end: "12:00", subject: "AI Lab", room: "AI Lab" }],
      Friday: [{ start: "09:00", end: "10:00", subject: "Machine Learning", room: "JW101" }],
    },
  };

  const facultyDocs = await Faculty.find({});
  for (const f of facultyDocs) {
    f.passwordHash = bcrypt.hashSync(FAC_PASSWORD, 10);
    const tt = sampleTimetables[f.email];
    if (tt) f.timetable = tt;
    f.refreshAvailability();
    await f.save();
  }

  await PointOfInterest.insertMany([
    {
      type: "block",
      name: "Visvesvaraya Bhavan",
      block: "Visvesvaraya Bhavan",
      floor: "Ground Floor",
      latitude: 17.0895,
      longitude: 82.0668,
      openHours: "9:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "ACET (Aditya College of Engineering & Technology) administrative building housing the B.Tech ECE department along with college administration, examination cell, admissions and transport office. Allocation: Verified department building.",
    },
    {
      type: "block",
      name: "Ramanujan Bhavan",
      block: "Ramanujan Bhavan",
      floor: "1st Floor",
      latitude: 17.0898,
      longitude: 82.0670,
      openHours: "8:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "ACET academic building hosting B.Tech Computer Science & Engineering (1st - 4th year) with classrooms and programming labs. Allocation: Verified.",
    },
    {
      type: "block",
      name: "Newton Bhavan",
      block: "Newton Bhavan",
      floor: "2nd Floor",
      latitude: 17.0897,
      longitude: 82.0671,
      openHours: "8:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "ACET academic building hosting B.Tech Information Technology (1st - 4th year) with web, cloud and data structures labs. Allocation: Verified.",
    },
    {
      type: "block",
      name: "James Watt Bhavan",
      block: "James Watt Bhavan",
      floor: "Ground + 1st Floor",
      latitude: 17.0900,
      longitude: 82.0672,
      openHours: "8:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "ACET academic building hosting B.Tech Artificial Intelligence & Machine Learning, B.Tech Data Science and IoT-related programs with AI, ML and data science labs. Allocation: Verified grouping.",
    },
    {
      type: "block",
      name: "C.V. Raman Bhavan",
      block: "C.V. Raman Bhavan",
      floor: "Ground - 2nd Floor",
      latitude: 17.0894,
      longitude: 82.0674,
      openHours: "8:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "ACET department building hosting B.Tech Electrical & Electronics Engineering, Mechanical Engineering and Civil Engineering (1st - 4th year) with workshop, CAD, concrete and power systems labs. Allocation: Verified department building.",
    },
    {
      type: "block",
      name: "Cotton Bhavan",
      block: "Cotton Bhavan",
      floor: "Ground + 1st Floor",
      latitude: 17.0889,
      longitude: 82.0675,
      openHours: "8:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "Aditya University academic building planned for B.Tech Agricultural Engineering and B.Tech Mining Engineering (1st - 4th year). Allocation: Proposed.",
    },
    {
      type: "block",
      name: "Ratan Tata Bhavan",
      block: "Ratan Tata Bhavan",
      floor: "Ground + 1st Floor",
      latitude: 17.0891,
      longitude: 82.0672,
      openHours: "8:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "Aditya University academic building planned for B.Tech Petroleum Technology and M.Tech Energy Science & Technology. Allocation: Proposed.",
    },
    {
      type: "block",
      name: "Bill Gates Bhavan",
      block: "Bill Gates Bhavan",
      floor: "Ground Floor",
      latitude: 17.0899,
      longitude: 82.0662,
      openHours: "8:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "Aditya University academic building for B.Tech CSE (Data Science) and Bachelor of Computer Applications (BCA). Allocation: Proposed.",
    },
    {
      type: "block",
      name: "K.L. Rao Bhavan",
      block: "K.L. Rao Bhavan",
      floor: "Proposed",
      latitude: 17.0893,
      longitude: 82.0662,
      openHours: "8:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "Aditya University academic building planned for B.Tech Civil Engineering, M.Tech Structural Engineering and M.Sc Real Estate Valuation. Allocation: Proposed.",
    },
    {
      type: "block",
      name: "Bhaskara Bhavan",
      block: "Bhaskara Bhavan",
      floor: "UG 2nd - 4th Year",
      latitude: 17.0890,
      longitude: 82.0670,
      openHours: "8:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "Aditya University building for B.Tech Agricultural Engineering laboratories, shared engineering labs and research activity. Allocation: Proposed.",
    },
    {
      type: "block",
      name: "Aditya Degree & PG College",
      block: "Aditya Degree & PG College",
      floor: "Ground - 2nd Floor",
      latitude: 17.0899,
      longitude: 82.0666,
      openHours: "9:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "Aditya Degree College, Surampalem campus hosting BBA, BBA Digital Marketing, B.Sc Forensic Science, B.Sc Animation, B.Sc Artificial Intelligence & Robotics, B.Sc Data Science and B.Sc Cyber Forensics along with MCA and MBA. Programs verified; exact room allocation is dynamic.",
    },
    {
      type: "block",
      name: "Aditya Pharmacy College",
      block: "Aditya Pharmacy College",
      floor: "Ground Floor",
      latitude: 17.0901,
      longitude: 82.0665,
      openHours: "9:00 AM - 5:00 PM",
      isOpenNow: true,
      description:
        "Pharmacy academic zone of Aditya University for B.Pharm (1st - 4th year) and Pharm.D (1st - 6th year) with chemistry, pharmacognosy and pharmacology labs. Program verified; building allocation proposed.",
    },
    {
      type: "block",
      name: "Aditya College of Pharmacy",
      block: "Aditya College of Pharmacy",
      floor: "1st - 2nd Year",
      latitude: 17.0902,
      longitude: 82.0663,
      openHours: "9:00 AM - 5:00 PM",
      isOpenNow: true,
      description:
        "Postgraduate pharmacy college of Aditya University for M.Pharm Pharmaceutics and M.Pharm Pharmaceutical Analysis with advanced pharmacy labs and research activity. Program verified; building allocation proposed.",
    },
    {
      type: "block",
      name: "Abdul Kalam Bhavan",
      block: "Abdul Kalam Bhavan",
      floor: "Diploma 1st Year",
      latitude: 17.0902,
      longitude: 82.0671,
      openHours: "9:00 AM - 5:00 PM",
      isOpenNow: true,
      description:
        "Aditya Polytechnic College building for polytechnic administration, examination cell and common first-year diploma classes. Allocation: Verified.",
    },
    {
      type: "block",
      name: "Einstein Bhavan",
      block: "Einstein Bhavan",
      floor: "Diploma 2nd - 3rd Year",
      latitude: 17.0903,
      longitude: 82.0674,
      openHours: "9:00 AM - 5:00 PM",
      isOpenNow: true,
      description:
        "Aditya Polytechnic College department building for Diploma Civil Engineering, Diploma Electrical / EEE, Diploma Computer Engineering / CSE and Diploma Communication & Computer Networking. Allocation: Verified departments.",
    },
    {
      type: "block",
      name: "Edison Bhavan",
      block: "Edison Bhavan",
      floor: "Diploma 2nd - 3rd Year",
      latitude: 17.0902,
      longitude: 82.0677,
      openHours: "9:00 AM - 5:00 PM",
      isOpenNow: true,
      description:
        "Aditya Polytechnic College department building for Diploma Mechanical Engineering and Diploma ECE. Allocation: Verified.",
    },
    {
      type: "block",
      name: "Aditya Polytechnic College (Shared)",
      block: "Aditya Polytechnic College",
      floor: "Diploma 1st - 3rd Year",
      latitude: 17.0903,
      longitude: 82.0672,
      openHours: "9:00 AM - 5:00 PM",
      isOpenNow: true,
      description:
        "Shared polytechnic facilities, laboratories, workshops and overflow classes for the diploma programs. Allocation: Proposed as shared facility.",
    },
    {
      type: "block",
      name: "Main Auditorium",
      block: "Visvesvaraya Bhavan",
      floor: "1st Floor",
      latitude: 17.0896,
      longitude: 82.0672,
      openHours: "Event hours",
      isOpenNow: false,
      description: "Conference hall for seminars, technical fests and cultural programs.",
    },
    {
      type: "library",
      name: "Knowledge Resource Centre (Central Library)",
      block: "Library Block",
      floor: "Ground + 1st Floor",
      latitude: 17.0897,
      longitude: 82.0668,
      openHours: "8:00 AM - 8:00 PM",
      isOpenNow: true,
      description:
        "Central library with reading rooms, reference section, e-journal access, and digital library. Open throughout the day for faculty and students.",
    },
    {
      type: "shop",
      name: "Main Food Court",
      block: "Near Ramanujan Bhavan",
      latitude: 17.0898,
      longitude: 82.0674,
      openHours: "8:00 AM - 9:00 PM",
      isOpenNow: true,
      items: [
        { name: "Idly (2)", price: 30, available: true },
        { name: "Dosa", price: 45, available: true },
        { name: "Veg Biryani", price: 90, available: true },
        { name: "Fried Rice", price: 80, available: false },
        { name: "Filter Coffee", price: 20, available: true },
        { name: "Tea", price: 15, available: true },
      ],
    },
    {
      type: "shop",
      name: "Student Canteen",
      block: "Near Edison Bhavan",
      latitude: 17.0899,
      longitude: 82.0678,
      openHours: "9:00 AM - 6:00 PM",
      isOpenNow: true,
      items: [
        { name: "Samosa", price: 20, available: true },
        { name: "Cold Coffee", price: 40, available: true },
        { name: "Maggi", price: 45, available: true },
        { name: "Vada", price: 25, available: false },
      ],
    },
    {
      type: "shop",
      name: "Stationery & Photocopy",
      block: "Near Visvesvaraya Bhavan",
      latitude: 17.0895,
      longitude: 82.0667,
      openHours: "9:00 AM - 5:00 PM",
      isOpenNow: true,
      items: [
        { name: "Photocopy (per page)", price: 2, available: true },
        { name: "Printout (per page)", price: 3, available: true },
        { name: "Spiral Binding", price: 40, available: true },
        { name: "Notebook", price: 60, available: true },
      ],
    },
    {
      type: "service",
      name: "Bank & ATM",
      block: "Visvesvaraya Bhavan",
      floor: "Ground Floor",
      latitude: 17.0894,
      longitude: 82.0667,
      openHours: "24 hours (ATM)",
      isOpenNow: true,
      description: "On-campus bank branch and 24x7 ATM for hostel students and staff.",
    },
    {
      type: "service",
      name: "Medical Centre",
      block: "Near K.L. Rao Bhavan",
      latitude: 17.0893,
      longitude: 82.0667,
      openHours: "24 hours",
      isOpenNow: true,
      description:
        "Round-the-clock medical centre with resident doctor, first aid and emergency ambulance facility.",
    },
    {
      type: "ground",
      name: "Sports Complex & Grounds",
      block: "East of C.V. Raman Bhavan",
      latitude: 17.0892,
      longitude: 82.0679,
      openHours: "6:00 AM - 8:00 PM",
      isOpenNow: true,
      description:
        "Cricket and football grounds, volleyball and basketball courts, indoor games room and gymnasium.",
      accessPolicy: {
        allowedRoles: ["student", "faculty"],
        restrictedRoles: [],
        startTime: "06:00",
        endTime: "20:00",
        note: "Sports facilities open to students and faculty from 6:00 AM to 8:00 PM; closed for booking by departments during events.",
      },
    },
    {
      type: "ground",
      name: "Transport Hub (Bus Bay)",
      block: "Main Gate",
      latitude: 17.0896,
      longitude: 82.0678,
      openHours: "5:00 AM - 9:00 PM",
      isOpenNow: true,
      description:
        "College bus boarding point. Buses connect Surampalem campus to Kakinada, Samalkot, Peddapuram and surrounding mandals.",
    },
    {
      type: "office",
      name: "Career Development Centre",
      block: "Visvesvaraya Bhavan",
      floor: "1st Floor",
      latitude: 17.0896,
      longitude: 82.0669,
      openHours: "9:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "Placement training, aptitude coaching, internships, and on-campus recruitment cell.",
    },
    {
      type: "office",
      name: "Aditya Genesis Business Incubator (AGBI)",
      block: "Near Cotton Bhavan",
      latitude: 17.0891,
      longitude: 82.0677,
      openHours: "9:00 AM - 6:00 PM",
      isOpenNow: true,
      description:
        "Campus innovation facility for startup incubation, interdisciplinary projects, entrepreneurship programs and hackathons. Facility, not a single branch - open to students from all years and programs.",
    },
    {
      type: "office",
      name: "Centre for Technical Training",
      block: "Ramanujan Bhavan",
      floor: "2nd Floor",
      latitude: 17.0898,
      longitude: 82.0671,
      openHours: "10:00 AM - 5:00 PM",
      isOpenNow: true,
      description:
        "Skill development programmes, coding clubs and industry-oriented technical training (IGNITE, campus to corporate).",
    },
    {
      type: "hostel",
      name: "Boys Hostel",
      block: "Hostel Block A",
      latitude: 17.0900,
      longitude: 82.0680,
      openHours: "24 hours",
      isOpenNow: true,
      hostelType: "boys",
      warden: "Mr. V. V. S. Murthy",
      contact: "+91 98490 00121",
      totalRooms: 220,
      vacantRooms: 14,
    },
    {
      type: "hostel",
      name: "Girls Hostel",
      block: "Hostel Block B",
      latitude: 17.0902,
      longitude: 82.0678,
      openHours: "24 hours",
      isOpenNow: true,
      hostelType: "girls",
      warden: "Mrs. N. Padmavathi",
      contact: "+91 98490 00122",
      totalRooms: 260,
      vacantRooms: 9,
      accessPolicy: {
        allowedRoles: ["student", "faculty"],
        restrictedRoles: ["external"],
        startTime: "05:00",
        endTime: "22:00",
        note: "Girls hostel access for visitors is limited to 5:00 AM - 10:00 PM; hostellers have 24x7 access.",
      },
    },
  ]);

  await BusRoute.insertMany([
    {
      routeNumber: "K-1",
      routeDescription: "Surampalem Campus -> Kakinada (via Chidambaranagar, Sarpavaram, Jagannaickpur)",
      stops: [
        { name: "Campus Gate", time: "6:45 AM" },
        { name: "Surampalem Junction", time: "6:50 AM" },
        { name: "Chidambaranagar", time: "7:05 AM" },
        { name: "Innespeta", time: "7:15 AM" },
        { name: "Sarpavaram", time: "7:25 AM" },
        { name: "Jagannaickpur", time: "7:35 AM" },
        { name: "Gandhinagar", time: "7:50 AM" },
      ],
      departureTime: "6:45 AM",
      returnTime: "5:30 PM",
      driverName: "Mr. P. Ramesh",
      driverContact: "+91 98490 00231",
      status: "On Route",
    },
    {
      routeNumber: "K-2",
      routeDescription: "Surampalem Campus -> Kakinada City (via Samalkot, Gollaprolu, Kondayyapalem)",
      stops: [
        { name: "Campus Gate", time: "7:00 AM" },
        { name: "Samalkot", time: "7:20 AM" },
        { name: "Gollaprolu", time: "7:35 AM" },
        { name: "Kondayyapalem", time: "7:50 AM" },
        { name: "Bhanugudi Junction", time: "8:00 AM" },
        { name: "Kakinada City", time: "8:10 AM" },
      ],
      departureTime: "7:00 AM",
      returnTime: "5:45 PM",
      driverName: "Mr. S. Krishna Murthy",
      driverContact: "+91 98490 00232",
      status: "Diesel Station",
    },
    {
      routeNumber: "P-3",
      routeDescription: "Surampalem Campus -> Peddapuram (via Rangampeta, Prathipadu)",
      stops: [
        { name: "Campus Gate", time: "7:10 AM" },
        { name: "Rangampeta", time: "7:30 AM" },
        { name: "Prathipadu", time: "7:45 AM" },
        { name: "Peddapuram", time: "8:05 AM" },
      ],
      departureTime: "7:10 AM",
      returnTime: "4:30 PM",
      driverName: "Mr. N. Suryanarayana",
      driverContact: "+91 98490 00233",
      status: "On Route",
    },
  ]);

  await Event.insertMany([
    {
      title: "IGNITE 2026 - Coder Dot. Connect",
      description:
        "The flagship technical skill-development program by the Centre for Technical Training. Daily coding challenges, hands-on sessions and mentor connect for all branches and years.",
      date: "2026-09-15",
      startTime: "10:00 AM",
      endTime: "4:00 PM",
      venue: "Centre for Technical Training, Ramanujan Bhavan",
      organizer: "Centre for Technical Training",
      department: "ALL",
      category: "Technical",
    },
    {
      title: "AP State-wide Quantum Awareness Program",
      description:
        "A state-wide awareness session on quantum computing and quantum technologies organised for engineering and computing students.",
      date: "2026-09-16",
      startTime: "10:00 AM",
      endTime: "1:00 PM",
      venue: "Main Auditorium",
      organizer: "School of Engineering & School of Computing",
      department: "ALL",
      category: "Technical",
    },
    {
      title: "Internal Hackathon for Smart India Hackathon 2026",
      description:
        "University-level internal hackathon to shortlist teams for Smart India Hackathon 2026, with problem statements across smart automation, healthcare, and sustainability.",
      date: "2026-09-18",
      startTime: "9:00 AM",
      endTime: "5:00 PM",
      venue: "AGBI Innovation Hub",
      organizer: "IIC & Institution's Innovation Council",
      department: "ALL",
      category: "Technical",
    },
    {
      title: "MOU Exchange & Orientation - IDP Education",
      description:
        "Memorandum of understanding exchange and orientation session with IDP Education for IELTS preparation and international study opportunities (Australia, UK, Canada).",
      date: "2026-09-17",
      startTime: "11:00 AM",
      endTime: "1:00 PM",
      venue: "Seminar Hall, Visvesvaraya Bhavan",
      organizer: "School of Computing",
      department: "ALL",
      category: "Workshop",
    },
    {
      title: "Parents & Students Orientation - I B.Pharm & I Pharm.D",
      description:
        "Orientation for first-year pharmacy students and their parents covering curriculum, attendance, hostel and campus life.",
      date: "2026-09-23",
      startTime: "10:00 AM",
      endTime: "12:00 PM",
      venue: "Aditya Pharmacy College",
      organizer: "School of Pharmacy",
      department: "PHA",
      category: "Orientation",
    },
    {
      title: "Alumni Interaction - Careers in Civil Engineering",
      description:
        "Session with alumni working in construction, structural design and infrastructure to guide final-year Civil Engineering students on career paths.",
      date: "2026-09-24",
      startTime: "2:00 PM",
      endTime: "3:30 PM",
      venue: "Seminar Hall, C.V. Raman Bhavan",
      organizer: "Department of Civil Engineering",
      department: "CE",
      category: "Alumni",
    },
    {
      title: "Alumni Interaction - Smart Factories & Digital Manufacturing",
      description:
        "Alumni-led session on Industry 4.0, smart factories and digital manufacturing for Mechanical Engineering students.",
      date: "2026-09-25",
      startTime: "2:00 PM",
      endTime: "3:30 PM",
      venue: "Seminar Hall, C.V. Raman Bhavan",
      organizer: "Department of Mechanical Engineering",
      department: "ME",
      category: "Alumni",
    },
    {
      title: "Telugu Bhasha Dinotsavam 2026",
      description:
        "Celebration of Telugu Language Day with literary competitions, poetry recitals and classical music at the Knowledge Resource Centre.",
      date: "2026-09-30",
      startTime: "4:00 PM",
      endTime: "6:00 PM",
      venue: "Knowledge Resource Centre",
      organizer: "Central Library (KRC)",
      department: "ALL",
      category: "Cultural",
    },
  ]);

  console.log("Seed data inserted successfully.");
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seeding failed:", err);
  process.exit(1);
});